---
title: "phenomix"
author: "Brian M. Schilder"
date: "2023-11-10"
output: html_document
---


# Phenotype x celltype enrichment tests

```{r} 
ymat <- HPOExplorer::hpo_to_matrix(formula = "gene_symbol ~ hpo_id")
run_phenomix <- function(ctd_name,
                         annotLevel,
                         ymat,
                         save_path = here::here(
                           "results",
                           paste0("phenomix_",ctd_name,"_results.tsv.gz")
                           ),
                         metric="specificity_quantiles",
                         workers = NULL,
                         force_new = FALSE,
                         ...
                         ){
  if(file.exists(save_path) && isFALSE(force_new)){
    message("Loading existing results from ",save_path)
    return(data.table::fread(save_path))
  }
  ctd <- MSTExplorer::load_example_ctd(file = paste0("ctd_",ctd_name,".rds"))
  xmat <- ctd[[annotLevel]][[metric]] 
  lm_res <- phenomix::iterate_lm(xmat = xmat, 
                                 ymat = ymat, 
                                 method="glm",
                                 correction_method = "fdr",
                                 workers = workers,
                                 ...)
  lm_res[,annotLevel:=annotLevel]
  data.table::fwrite(lm_res,save_path)
  return(lm_res)
}



lm_res1 <- run_phenomix(ctd_name = "DescartesHuman",
                        annotLevel = 2,
                        force_new = TRUE,
                        ymat = ymat) 
lm_res2 <- run_phenomix(ctd_name = "HumanCellLandscape",
                        annotLevel = 3,
                        force_new = TRUE,
                        ymat = ymat)
lm_res <- data.table::rbindlist(list(DescartesHuman=lm_res1,
                                     HumanCellLandscape=lm_res2),
                                idcol = "ctd")
#### Multiple-testing correction ####
## For GLM (all celltypes/model)
lm_res[,q:=ifelse(model_q<0.05,p,min(1,model_q+p)), by=.I]  
## For ANOVA (1 celltype/model)
# lm_res[,q:=stats::p.adjust(p,method="fdr")] 


data.table::setnames(lm_res,
                     c("xvar","yvar","F"),
                     c("hpo_id","CellType","fold_change"))
# f <- here::here("results/phenomix_results.tsv.gz")
# data.table::fwrite(lm_res,f)
# piggyback::pb_upload(file = f, repo = "neurogenomics/MSTExplorer")

lm_res <- HPOExplorer::add_hpo_name(lm_res)
lm_res <- MSTExplorer::map_celltype(lm_res)

top_res <- lm_res[q<0.05]|> 
    dplyr::group_by(hpo_id) |> 
    dplyr::slice_max(order_by = fold_change, n = 1) |>
    dplyr::arrange(dplyr::desc(fold_change))  |>
    data.table::data.table()

View(top_res)
```

### Compare MultiECWE vs. phenomix results

```{r}
res <- MSTExplorer::load_example_results("rare_disease_min_genes4_DescartesHuman.rds")
res_merged <- merge(
    (lm_res|> 
         data.table::setnames(c("xvar","yvar","F"),c("hpo_id","CellType","fold_change"),
                              skip_absent = TRUE))[,c("hpo_id","CellType","p","q","fold_change")],
    res[,c("hpo_id","CellType","p","q","fold_change")],
    by=c("hpo_id","CellType"),
    suffixes = c("_phenomix","_MSTExplorer")
)[,cs_MSTExplorer:=(1-q_MSTExplorer)*fold_change_MSTExplorer][,cs_phenomix:=(1-q_phenomix)*fold_change_phenomix]

ct_p <- cor.test(res_merged$p_MSTExplorer,res_merged$p_phenomix)
ct_q <- cor.test(res_merged$q_MSTExplorer,res_merged$q_phenomix)
ct_fc <- cor.test(res_merged$fold_change_MSTExplorer,res_merged$fold_change_phenomix)
ct_cs <- cor.test(res_merged$cs_MSTExplorer,res_merged$cs_phenomix)
# lm(res_merged$fold_change_MSTExplorer~res_merged$fold_change_phenomix) |> summary()

## Compare overlap in top CellType per hpo_id via each method
res_top <- res_merged[q_MSTExplorer<.05,.(CellType_phenomix=CellType[which.max(fold_change_phenomix)],
              CellType_MSTExplorer=CellType[which.max(fold_change_MSTExplorer)]),
           by=hpo_id][,matched:=CellType_phenomix==CellType_MSTExplorer]
res_top <- res_merged[q_MSTExplorer<.05,.(CellType_phenomix=CellType[which.min(p_phenomix)],
                                        CellType_MSTExplorer=CellType[which.min(p_MSTExplorer)]),
                      by=hpo_id][,matched:=CellType_phenomix==CellType_MSTExplorer]
sum(res_top$matched)/nrow(res_top)*100


library(ggplot2)
ggplot(res_merged,
       aes(x=-log10(q_MSTExplorer+1e-100),
           y=-log10(q_phenomix+1e-100),
           color=q_phenomix))+
    geom_point(show.legend = FALSE)+
    # facet_wrap(~CellType,scales = "free")+
    theme_bw()
ggplot(res_merged,
       aes(x=log10(scales::rescale(fold_change_MSTExplorer)),
           y=log10(scales::rescale(fold_change_phenomix)),
           color=CellType))+
    geom_point(show.legend = FALSE)+
    # facet_wrap(~CellType,scales = "free")+
    theme_bw()
```

 

# Seurat processing 

```{r}
id_types = c("disease_id","hpo_id")
dt_genes <-  HPOExplorer::load_phenotype_to_genes(1)
dt_genes[,symptom_id:=paste(disease_id,hpo_id,sep=".")]
dt_genes <- HPOExplorer::add_evidence(dt_genes)
ev <- dt_genes[,list(evidence_score_grouped=mean(evidence_score_mean)),by=id_types]
dt_annot <- HPOExplorer::make_phenos_dataframe(
    phenotype_to_genes = dt_genes,
    add_disease_data = TRUE,
    add_hoverboxes = FALSE)
dt_annot <- dt_annot[ev,on=id_types]
dt_annot[,symptom_id:=paste(disease_id,hpo_id,sep=".")]
dt_genes <- dt_genes[symptom_id %in% unique( dt_annot$symptom_id),]

dt_annot <- HPOExplorer::add_disease_definition(dt_annot)
dt_annot[,DEFINITION:=data.table::fcoalesce(definition,Definitions,hpo_name,disease_name)]

obj <- prepare_hpo(dt_genes = dt_genes,
                   dt_annot = dt_annot,
                   id_types= id_types,
                   vars.to.regress = c("n_genes"),
                   run_nlp=FALSE)

obj$n_genes_log <- log10(obj$n_genes)
Seurat::FeaturePlot(obj, 
                    features = "n_genes_log",
                    alpha = .5)


scnlp_res <- scNLP::plot_tfidf(
    obj,
    label_var = "DEFINITION",
    terms_per_cluster = 1,
    size_var = "n_genes",
    point_size = .5,
    point_palette = pals::kovesi.cyclic_mrybm_35_75_c68_s25(
        length(unique(obj@meta.data[["seurat_clusters"]]))
    )
)



# xmat <- scKirby::get_x(obj,
#                        slot="scale.data",
#                        n=1)
```

# Session info

<details>
```{r}
utils::sessionInfo()

```
</details>
