{
  "hash": "3c26955667fe8b02f75b36311beaee42",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cell type-specific contextualisation of the phenomic landscape: a comprehensive and scalable approach towards the diagnosis, prognosis and treatment of all rare diseases\"\nauthor:\n  - name: Brian M. Schilder\n    orcid: 0000-0001-5949-2191\n    corresponding: true\n    email: brian_schilder@alumni.brown.edu\n    roles:\n      - Investigation\n      - Project administration\n      - Software\n      - Visualization\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: Department of Brain Sciences\n      - name: UK Dementia Research Institute\n        city: London\n        country: United Kingdom\n  - name: Kitty B. Murphy\n    orcid: 0000-0002-8669-3076\n    corresponding: false\n    roles:\n      - Investigation \n      - Software\n      - Visualization\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: Department of Brain Sciences\n      - name: UK Dementia Research Institute\n        city: London\n        country: United Kingdom\n  - name: Robert Gordon-Smith\n    orcid: 0000-0001-6698-7387\n    corresponding: false\n    roles:\n      - Investigation \n      - Software\n      - Visualization\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: Department of Brain Sciences\n      - name: UK Dementia Research Institute\n        city: London\n        country: United Kingdom\n  - name: Jai Chapman\n    corresponding: false\n    roles:\n      - Investigation \n      - Software\n      - Visualization\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: Department of Brain Sciences\n      - name: UK Dementia Research Institute\n        city: London\n        country: United Kingdom\n  - name: Momoko Otani\n    corresponding: false\n    roles:\n      - Investigation\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: National Heart and Lung Institute\n  - name: Nathan G. Skene\n    orcid: 0000-0002-6807-3180\n    corresponding: true\n    email: n.skene@imperial.ac.uk\n    roles:\n      - Project administration\n    affiliations:\n      - name: Imperial College London\n        city: London\n        country: United Kingdom\n        department: Department of Brain Sciences\n      - name: UK Dementia Research Institute\n        city: London\n        country: United Kingdom\nkeywords:\n  - rare disease\n  - phenotype\n  - single-cell\n  - gene therapy\nplain-language-summary: |\n  We identified the cell types underlying the symptoms of all rare diseases.\nkey-points:\n  - We used the Human Phenotype Ontology and single-cell RNA-seq references to characterise the phenome.\n  - We then demonstrated how these results can be applied to clinical diagnosis, prognosis and therapeutics development.\ndate: last-modified\nbibliography: references.bib\ncitation:\n  container-title: Nature Medicine\nformat:\n  nature-pdf:\n    journal: \"sn-nature\"\n    keep-tex: true\n    execute:\n      cache: true\n      echo: false\n  docx:\n    execute:\n      cache: true\n      echo: false\n---\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(data.table)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nhpo <- HPOExplorer::get_hpo()\np2g <- HPOExplorer::load_phenotype_to_genes()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nannot <- HPOExplorer::load_phenotype_to_genes(3)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nper_disease <- p2g[,list(ng=data.table::uniqueN(gene_symbol),\n                         np=data.table::uniqueN(hpo_id)),by=\"disease_id\"]\nper_phenotype <- p2g[,list(ng=data.table::uniqueN(gene_symbol),\n                           nd=data.table::uniqueN(disease_id)),by=\"hpo_id\"]\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Import precomputed results for reporting summaries\nresults <- MSTExplorer::load_example_results()\nresults <- HPOExplorer::add_hpo_name(results, hpo = hpo)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding HPO names.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to names.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nresults <- HPOExplorer::add_ont_lvl(results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting absolute ontology level for 18,082 IDs.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nresults <- HPOExplorer::add_ancestor(results, hpo = hpo)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding level-2 ancestor to each HPO ID.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding ancestor metadata.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAncestor metadata already present. Use force_new=TRUE to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,206,994 associations remain after filtering.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nresults <- MSTExplorer::map_celltype(results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMapping cell types to cell ontology terms.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding stage information.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nMSTExplorer::add_logfc(results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding logFC column.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nresults[,effect:=estimate]\n## Substitute B for \\beta for now since Quarto doesn't seem to support\n## Greek letters after they've been stored in a data.table...\nresults[,summary:=paste0(\n  \"$\",\n  \"FDR_{p,c}=\",format(q,digits=3),\",\",\n  \"B=\",format(estimate,digits=3),\n  \"$\"\n)] \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nres_summ <- MSTExplorer::summarise_results(results = results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving results --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//Rtmp91iLYI/summarise_results.csvf4eb4104ce28\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nres_summ_all <- res_summ$tmerged[ctd==\"all\"] \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Must use `cache.lazy=FALSE` because sparse matrices not yet supported for caching\nctd_list <- MSTExplorer::load_example_ctd(c(\"ctd_DescartesHuman.rds\",\n                                           \"ctd_HumanCellLandscape.rds\"),\n                                          multi_dataset=TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_DescartesHuman.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_HumanCellLandscape.rds\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nvalidate_associations_mkg_out <- MSTExplorer::validate_associations_mkg(results = results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nℹ All local files already up-to-date!\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRemaining: 82 phenotypes across 65 celltypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n90.24% phenotypes recovered.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nkg_hp <- validate_associations_mkg_out$kg[grepl(\"^HP:\",from)]\nX <- \"`**!!RECOMPUTE!!**`\"\nY <- \"`**!!RECOMPUTE!!**`\"\n```\n:::\n\n{{< pagebreak >}}\n\n\n\n\n\n## Abstract\n\nRare diseases (RDs) are an extremely heterogeneous and underserved category of medical conditions. While the majority of RDs are strongly genetic, it remains largely unknown via which physiological mechanisms genetics cause RD. Therefore, we sought to systematically characterise the cell type-specific mechanisms underlying all RD phenotypes with a known genetic cause by leveraging the Human Phenotype Ontology and transcriptomic single-cell atlases of the entire human body from embryonic, foetal, and adult samples. In total we identified significant associations between 201 cell types and 9,575/11,028 (86.7%) unique phenotypes across 8,628 RDs. We estimate that this represents an over 500-fold increase in the collective knowledge of RD phenotype-cell type mechanisms.\n\nNext, we demonstrated how these results may be used for personalised patient diagnosis and prognosis, as well as the development of novel therapeutics. Finally, we take a data-driven approach to highlight several of the most promising gene/cell therapy candidates with the highest probability of animal model-to-human patient translation. Furthermore, we have made these results entirely reproducible and freely accessible to the global community to maximise their impact. To summarise, this work represents a significant step forward in the mission to treat patients across an extremely diverse spectrum of serious RDs.\n\n## Introduction {#sec-introduction}\n\nWhile rare diseases (RDs) are individually uncommon, they collectively account for an enormous global disease burden with over 10,000 recognised RDs affecting at least 300-400 million people globally [@Ferreira2019-jp] (1 in 10-20 people) [@Zhu2020-vo] . Over 75% of RDs primarily affect children with a 30% mortality rate by 5 years of age [@noauthor_undated-kp]. Despite the prevalence and severity of RDs, patients suffering from these conditions are vastly underserved due to several contributing factors. First, diagnosis is extremely challenging due to the highly variable clinical presentations of many of these diseases. The diagnostic odyssey can take patients and their families decades, with an average time to diagnosis of 5 years [@Marwaha2022-uy]. Of those, \\~46% receive at least one incorrect diagnosis and over 75% of all patients never receive any diagnosis @Molster2016-da. Second, prognosis is also made difficult by high variability in disease course and outcomes which makes matching patients with effective and timely treatment plans even more challenging. Finally, even for patients who receive an accurate diagnosis/prognosis, treatments are currently only available for less than 5% of all RDs [@Halley2022-pd]. In addition to the scientific challenges of understanding RDs, there are strong financial disincentives for pharmaceutical and biotechnology companies to develop expensive therapeutics for exceedingly small RD patient populations with little or no return on investment [@Institute_of_Medicine_US_Committee_on_Accelerating_Rare_Diseases_Research_and_Orphan_Product_Development2010-vj; @Yates2022-ra]. Those that have been produced are amongst the world’s most expensive drugs, greatly limiting patients’ ability to access it [@Nuijten2022-yc; @Thielen2022-ud], The provision of timely, effective and affordable care for RD patients will require substantive transformations to our existing scientific, clinical, and regulatory frameworks.\n\nA major challenge in both healthcare and scientific research is the scalable exchange of information. Even in the age of electronic healthcare records (EHR) much of the information about an individual’s history is currently fractured across healthcare providers, often with differing nomenclatures for the same conditions. The Human Phenotype Ontology (HPO) is a hierarchically organised set of controlled clinical terms that provides a much needed common framework by which clinicians and researchers can precisely communicate patient conditions [@Gargano2024-fc; @Kohler2019-pc @Robinson2008-ys; @Kohler2021-wk]. The HPO spans all domains of human physiology and currently describes 18082 phenotypes across 10,300 RDs. Each phenotype and disease is assigned its own unique identifier and organised as a hierarchical graph, such that higher-level terms describe broad phenotypic categories or *branches* (e.g. *HP:0033127*: 'Abnormality of the musculoskeletal system' which contains 4495 unique phenotypes) and lower-level terms describe increasingly precise phenotypes (e.g. *HP:0030675*: \"Contracture of proximal interphalangeal joints of 2nd-5th fingers\"). It has already been integrated into healthcare systems and clinical diagnostic tools around the world, with increasing adoption over time [@Gargano2024-fc]. Common ontology-controlled frameworks like the HPO open a wealth of new opportunities, especially when addressing RDs. Services such as the Matchmaker Exchange [@Osmond2022-ml; @Philippakis2015-dq] have enabled the discovery of hundreds of underlying genetic etiologies, and led to the diagnosis of many patients. This also opens the possibility of gathering cohorts of geographically dispersed patients to run clinical trials, the only viable option for treatment in many individuals. To further increase the number of individuals who qualify for these treatments, as well as the trial sample size, proposals have been made deviate from the traditional single-disease clinical trial model and instead perform basket trials on groups of RDs with shared molecular etiologies (SaME) [@Zanello2023-zd]. However this approach, and indeed much of RD patient care, hinges upon first characterising the molecular mechanisms underlying each RD.\n\nOver 80% of RDs have a known genetic cause [@Nguengang_Wakap2020-cz; @noauthor_2022-ok]. Despite this our knowledge of the physiological mechanisms via which genetics cause pathogenesis is lacking for most RDs, severely hindering our ability to effectively diagnose, prognose and treat RD patients. The availability of standardised, ontology-controlled databases presents opportunities to systematically investigate RDs at scale. Since 2008, the HPO has been continuously updated using knowledge from the medical literature, as well as by integrating databases of expert validated gene-phenotype relationships, such as OMIM [@Amberger2019-vl; @Amberger2017-tg; @McKusick2007-di], Orphanet [@Maiella2013-oo; @Weinreich2008-wm], and DECIPHER @Firth2009-qg. A subset of the HPO contains gene annotations for 11,047 phenotypes across 8,631 diseases. Yet genes alone do not tell the full story of how RDs come to be, as their expression and functional relevance varies drastically across the multitude of tissues and cell types contained within the human body.\n\nOur knowledge of single-cell-resolution biology has exploded over the course of the last decade and a half, with numerous applications in both scientific and clinical practices [@Baysoy2023-vt; @Haque2017-bn; @Qi2023-ev]. More recently, comprehensive single-cell transcriptomic atlases across tissues have also emerged [@CZI_Single-Cell_Biology_Program2023-fs; @Svensson2020-lg]. In particular, the Descartes Human @Cao2020-qz and Human Cell Landscape @Han2020-iq projects provide comprehensive multi-system single-cell RNA-seq (scRNA-seq) atlases in embryonic, foetal, and adult human samples from across the human body. These datasets provide data-driven gene signatures for hundreds of cell subtypes. They also allow us to investigate disease mechanisms in the context of specific life stages.\n\nHere, we combine and extend several of the most comprehensive genomic and transcriptomic resources currently available to systematically uncover the cell types underlying granular phenotypes across 8,628 diseases. We then go on to highlight thousands of novel phenotype-cell type associations which collectively expand our knowledge of cell type-resolved phenotypes by an estimated 567-fold. Next, we present several potential avenues for real world applications of these results in the context of RD patient diagnosis, prognosis, treatment, and therapeutics development.\n\n## Results {#sec-results}\n\n### Phenotype-cell type associations\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Create phenotype-gene matrix filled with aggregated GenCC evidence scores\nymat <- HPOExplorer::hpo_to_matrix(formula = \"gene_symbol ~ hpo_id\")\n## Run phenomix with DescartesHuman CellTypeDataset\nlm_res1 <- MSTExplorer::run_phenomix(ctd_name = \"DescartesHuman\",\n                                     annotLevel = 2, \n                                     test_method = \"glm_univariate\",\n                                     ymat = ymat)\n## Run phenomix with HumanCellLandscape CellTypeDataset\nlm_res2 <- MSTExplorer::run_phenomix(ctd_name = \"HumanCellLandscape\",\n                                     annotLevel = 3, \n                                     test_method = \"glm_univariate\",\n                                     ymat = ymat)\n## Merge results\nresults <- data.table::rbindlist(list(DescartesHuman=lm_res1,\n                                      HumanCellLandscape=lm_res2),\n                                idcol = \"ctd\")\n## Apply multiple testing correction\nresults[,q:=stats::p.adjust(p,method=\"fdr\")]\n```\n:::\n\n\n\nIn this study we systematically investigated the cell types underlying phenotypes across the HPO. A summary of the phenome-wide results stratified by single-cell atlas can be found in @tbl-summary. Within the results using the Descartes Human single-cell atlas, 19,929/  848,078 (2.35%) tests across  77/ 77 (100%) cell types and 7,340/11,047 (66.4%) phenotypes revealed significant phenotype-cell type associations after multiple-testing correction ($FDR_{p,c}<0.05$). Using the Human Cell Landscape single-cell atlas, 26,585/1,358,916 (1.96%) tests across 124/124 (100%) cell types and 9,049/11,047 (81.9%) phenotypes showed significant phenotype-cell type associations ($FDR_{p,c}<0.05$). The median number of significantly associated phenotypes per cell type was 252 (Descartes Human) and 200 (Human Cell Landscape), respectively.\n\nAcross both single-cell references, the median number of significantly associated cell types per phenotype was 3, suggesting reasonable specificity of the testing strategy. 8,628/8,631 (\\~100%) of diseases within the HPO gene annotations showed significant cell type associations for at least one of their respective phenotypes.\n\n### Validation of expected phenotype-cell type relationships\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot_bar_dendro_out <- MSTExplorer::plot_bar_dendro(\n  results = results, \n  show_plot = FALSE) \n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: ggdendro\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAncestor columns already present. Skipping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,206,994 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltered 'ancestor_name' : 999,488 / 2,206,994 rows dropped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\ncardiocyte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading cached ontology: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/cl.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nendocrine cell\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nphotoreceptor cellretinal cell\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nleukocyte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\ncell of skeletal musclechondrocyte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nneural cell\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nrespiratory epithelial cellepithelial cell of lung\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading cached ontology: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/cl.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nConverted ontology to: igraph \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nConverted ontology to: igraph_dist \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to names.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: tol\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Invalid .internal.selfref detected and fixed by taking a (shallow)\ncopy of the data.table so that := can add this new column by reference. At an\nearlier point, this data.table has been copied by R (or was created manually\nusing structure() or similar). Avoid names<- and attr<- which in R currently\n(and oddly) may copy the whole data.table. Use set* syntax instead to avoid\ncopying: ?set, ?setnames and ?setattr. If this message doesn't help, please\nreport your use case to the data.table issue tracker so the root cause can be\nfixed or this message improved.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRunning tests: across_branches_per_celltype\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Invalid .internal.selfref detected and fixed by taking a (shallow)\ncopy of the data.table so that := can add this new column by reference. At an\nearlier point, this data.table has been copied by R (or was created manually\nusing structure() or similar). Avoid names<- and attr<- which in R currently\n(and oddly) may copy the whole data.table. Use set* syntax instead to avoid\ncopying: ?set, ?setnames and ?setattr. If this message doesn't help, please\nreport your use case to the data.table issue tracker so the root cause can be\nfixed or this message improved.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for x is already present.\nAdding another scale for x, which will replace the existing scale.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nScale for y is already present.\nAdding another scale for y, which will replace the existing scale.\nAncestor columns already present. Skipping.\n\n2,206,994 associations remain after filtering.\n\nCell type columns already present. Skipping mapping.\n\ncardiocyte\n\nTranslating ontology terms to ids.\n\nLoading cached ontology: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/cl.rds\n\nendocrine cell\n\nTranslating ontology terms to ids.\n\nphotoreceptor cellretinal cell\n\nTranslating ontology terms to ids.\n\nleukocyte\n\nTranslating ontology terms to ids.\n\ncell of skeletal musclechondrocyte\n\nTranslating ontology terms to ids.\n\nneural cell\n\nTranslating ontology terms to ids.\n\nrespiratory epithelial cellepithelial cell of lung\n\nTranslating ontology terms to ids.\n\nProportional enrichment summary stats:\n\n - pct_min: 17.22\n\n - pct_max: 64.86\n\n - pct_max_mean: 40.3\n\n - pct_max_sd: 16.36\n\n - enrichment_mean: 6.09\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\noverrep_dat <- plot_bar_dendro_out$ggbars_out$data_summary\n\noverrep_dat[,summary:=paste0(ancestor_name,\": \", \n                             n_celltypes_sig,\"/\",n_celltypes,\n                             \" types of \",shQuote(target_celltypes),\n                             \" were overrepresented\",\n                             \" ($N_{p}$=\",phenotypes_per_ancestor,\").\")] \n```\n:::\n\n\n\nWithin each high-level branch in the HPO shown in [Fig. @fig-summary]b, we tested whether each cell type was more often associated with phenotypes in that branch relative to those in all other branches (including those not shown). We then checked whether each cell type was overrepresented (at $FDR_{b,c}<0.05$) within its respective on-target HPO branch, where the number of phenotypes within that branch ($N_{p}$). Abnormality of the cardiovascular system: 5/6 types of 'cardiocyte' were overrepresented ($N_{p}$=673). Abnormality of the endocrine system: 3/4 types of 'endocrine cell' were overrepresented ($N_{p}$=291). Abnormality of the eye: 5/5 types of 'photoreceptor cell/retinal cell' were overrepresented ($N_{p}$=721). Abnormality of the immune system: 4/4 types of 'leukocyte' were overrepresented ($N_{p}$=255). Abnormality of the musculoskeletal system: 4/4 types of 'cell of skeletal muscle/chondrocyte' were overrepresented ($N_{p}$=2155). Abnormality of the nervous system: 19/23 types of 'neural cell' were overrepresented ($N_{p}$=1647). Abnormality of the respiratory system: 2/2 types of 'respiratory epithelial cell/epithelial cell of lung' were overrepresented ($N_{p}$=292)..\n\nAs an additional form of validation ([Fig. @fig-summary]d), we tested for a relationship between phenotype-cell type association significance ($-log_{e}(p_{p,c})$ where $log_{e}$ denotes natural log and and $p_{p,c}$ denotes uncorrected phenotype-cell type association p-values) and the proportion of on-target cell types. The list of on-target cell types were determined by matching each high-level HPO branch to a corresponding CL branch. These cross-ontology mappings can be found in @tbl-celltypes. For this analysis we used raw p-values ($p_{p,c}$) rather than multiple-testing corrected p-values ($FDR_{p,c}$) to provide a more dynamic range of values (as the latter can drive values to 1). All 7/7 high-level HPO branches showed a consistent upwards trend towards greater proportions of on-target cell types with increasing degrees of significance. Furthermore, all branches also showed a proportion of on-target cell types above that expected by chance (baseline = on-target cell types / total cell types) at $-log_{e}(p_{p,c})>1$.\n\n\n\n::: {#cell-fig-summary .cell}\n\n```{.r .cell-code .hidden}\nplot_bar_dendro_out$plot\n```\n\n::: {.cell-output-display}\n![Summary of significant associations between phenotypes and cell types, aggregated by HPO branch. Here we show **a**, the total number of significant phenotype enrichments per cell type ($FDR_{p,c}<0.05$) across all branches of the HPO. **b**, Number of phenotype association related to several high-level branches of the HPO. Asterisks above each bar indicate whether that cell type was significantly more often enriched in that branch relative to all other HPO branches, including those not shown here, as a proxy for how specifically that cell type is associated with that branch; $FDR _{b,c}<1e-04$ (\\*\\*\\*\\*), $FDR _{b,c}<0.001$ (\\*\\*\\*), $FDR_{b,c}<0.01$ (\\*\\*), $FDR _{b,c}<0.05$ (\\*). **c**, Dendrogram derived from the Cell Ontology (CL) showing the relatedness of all tested cell types to one another. For simplicity, cell type labels shown here are aligned to the CL [@Diehl2016-gt] and can therefore encompass one or more cell types annotated by the original authors of scRNA-seq datasets [@Cao2020-qz; @Han2020-iq]. **d**, Percentage of significant phenotype associations with on-target cell types (second row of facet labels), respective to the HPO branch. As significance increases ($-log_{10}(p)$ along the *x-axis*) the percentage of on-target enriched cell types also increases (*y-axis*).](index_files/figure-docx/fig-summary-1.png){#fig-summary}\n:::\n:::\n\n\n\n### Validation of inter- and intra-dataset consistency\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(data.table)\n## Across CTD\nvalidate_associations_correlate_ctd_out <- MSTExplorer::validate_associations_correlate_ctd(\n  results=results, \n  group_var=\"ctd\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCasting results.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n13 comparable celltypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n10945 comparable phenotypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n10 comparable celltypes @FDR<0.05.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n554 comparable phenotypes @FDR<0.05.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGenerating plots.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'ggside':\n  method from   \n  +.gg   ggplot2\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering statistics.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## Replace p-values of exactly 0 with smallest number R can compute\nvalidate_associations_correlate_ctd_out$data_stats$p.all$summary_data$p.value <- max(validate_associations_correlate_ctd_out$data_stats$p.all$summary_data$p.value,\n                  .Machine$double.xmin)\n\n## Within CTD: across developmental stages\nvalidate_associations_correlate_ctd_out_hcl <- MSTExplorer::validate_associations_correlate_ctd(\n  results=results,\n  filters= list(ctd=c(\"HumanCellLandscape\"), \n                stage=c(\"Fetus\",\"Adult\")),\n  group_var=\"stage\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltered 'ctd' : 848,078 / 2,206,994 rows dropped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltered 'stage' : 54,795 / 1,358,916 rows dropped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCasting results.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n38 comparable celltypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n10959 comparable phenotypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n33 comparable celltypes @FDR<0.05.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n1584 comparable phenotypes @FDR<0.05.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGenerating plots.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering statistics.\n```\n\n\n:::\n:::\n\n\n\nNext, we sought to validate the consistency of our results across the two single-cell reference datasets (Descartes Human vs. Human Cell Landscape) across the subset of overlapping cell types [Fig. @fig-ctd-correlation]. In total there were 142285 phenotype-cell type associations to compare across the two datasets (across 10945 phenotypes and 13 cell types annotated to the exact same CL term. We found that the correlation between p-values of the two datasets was high ($rho=0.492, p=1.08e-93$). Within the subset of results that were significant in both single-cell datasets ($FDR_{p,c}<0.05$), we found that correlation of the association effect size were even stronger ($rho=0.723, p=1.08e-93$). We also checked for the intra-dataset consistency between the p-values of the foetal and adult samples in the Human Cell Landscape, showing a very similar degree of correlation as the inter-dataset comparison ($rho=0.436, p=2.36e-149$). Together, these results suggest that our approach to identifying phenotype-cell type associations is highly replicable and generalisable to new datasets.\n\n### More specific phenotypes are associated with fewer genes and cell types\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot_ontology_levels_out <- MSTExplorer::plot_ontology_levels(\n  results = results, \n  ctd_list = ctd_list,\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: gginnards\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot_ontology_levels_out_stats <- plot_ontology_levels_out$data_stats$summary_data|>\n  data.table::setkeyv(\"parameter2\")\n## replace pvalues of exactly 0 with the minimum computable number in R\n## This avoids creating -Inf when logging values.\nplot_ontology_levels_out_stats[p.value==0, p.value:=.Machine$double.xmin]\nplot_ontology_levels_out_stats[q.value==0, q.value:=.Machine$double.xmin]\nplot_ontology_levels_out_stats[,summary:=paste0(\n  \"$\",\n  \"p=\",format(p.value,digits=3),\", \", \n  \"q=\",format(q.value,digits=3),\", \",\n  \"rho=\",format(estimate,digits=3),\n  \"$\"\n  )][,summary:=gsub(\"=[ ]\",\"=\",summary)]\n```\n:::\n\n\n\nFirst, we found that phenotype ontology showed a significant negative correlation with the number of genes annotated to that phenotype in the HPO data ([Fig. @fig-ontology-lvl]a; $p=2.23e-308, q=2.23e-308, rho=-0.2634$). This is expected as broader phenotypes tend to have large gene set annotations. Next, we reasoned that lower HPO ontology levels representing more specific phenotypes were likely to be associated with fewer, more specific subsets of cell types. This was indeed the case, as we observed a strongly significant negative correlation between the two variables ([Fig. @fig-ontology-lvl]b; $p=2.23e-308, q=2.23e-308, rho=-0.2927$). We also found that the effect size of significant phenotype-cell type associations ($FDR_{p,c}<0.05$) increased with greater phenotype specificity, though the relationship was rather weak ([Fig. @fig-ontology-lvl]c; $p=7.30e-97, q=7.30e-97, rho=0.0966$). Finally, we found that the mean expression specificity of phenotype-associated genes (within the cell types significantly associated with those respective phenotypes at $FDR_{p,c}<0.05$) was positively correlated phenotype ontology depth ([Fig. @fig-ontology-lvl]d; $p=2.71e-174, q=3.61e-174, rho=0.1398$).\n\n\n\n::: {#cell-fig-ontology-lvl .cell}\n\n```{.r .cell-code .hidden}\nplot_ontology_levels_out$plot\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n`geom_smooth()` using formula = 'y ~ x'\n```\n\n\n:::\n\n::: {.cell-output-display}\n![More specific phenotypes are associated with fewer, more specific genes and cell types. Box plots showing relationship between HPO phenotype level and **a**, the number of genes annotated to each phenotype, **b**, the number of significantly enriched cell types, **c**, the effect size of phenotype-cell type association tests at $FDR_{p,c}<0.05$, and **d**, the mean expression specificity of phenotype-associated genes in the cell types significantly associated with those respective phenotypes ($FDR_{p,c}<0.05$). Ontology level 0 represents the most inclusive HPO term 'All', while higher ontology levels (max=16) indicate progressively more specific HPO terms (e.g. 'Contracture of proximal interphalangeal joints of 2nd-5th fingers'). Boxes are coloured by the mean value (respective to the subplot) within each HPO level.](index_files/figure-docx/fig-ontology-lvl-1.png){#fig-ontology-lvl}\n:::\n:::\n\n\n\n### Hepatoblasts have a unique role in recurrent Neisserial infections\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nresults_tmp <- HPOExplorer::add_ancestor(data.table::copy(results),\n                                         lvl = 7,\n                                         force_new = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nForce new. Removing existing ancestor columns.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding level-7 ancestor to each HPO ID.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding ancestor metadata.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting absolute ontology level for 18,082 IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n3027 ancestors found at level 7\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to names.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,206,994 associations remain after filtering.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ntarget_branches <- list(\"Recurrent bacterial infections\"=\"leukocyte\")\ninfections_out <- MSTExplorer::plot_bar_dendro_facets(\n  results=results_tmp,\n  target_branches=target_branches,\n  facets = \"hpo_name\",\n  legend.position=\"top\",\n  lvl=9,\n  ncol=2,\n  vlines=\"hepatoblast\",\n  fill_var=\"ancestor_name_original\",\n  facets_n=NULL,\n  q_threshold=0.05,\n  background_full=FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nForce new. Removing existing ancestor columns.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding level-9 ancestor to each HPO ID.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding ancestor metadata.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting absolute ontology level for 18,082 IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2384 ancestors found at level 9\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to names.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,206,994 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nKeeping descendants of 1 term(s).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n20 terms remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n4,020 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nleukocyte\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading cached ontology: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/cl.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRunning tests: across_branches_per_celltype\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\nSkipping tests.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: gnuplot\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nremove(results_tmp)\n\nstaph_res <- infections_out$data[hpo_name==\"Recurrent staphylococcal infections\"]\nstaph_res_top <- staph_res[,.SD[p %in% head(sort(p), 1)], by=c(\"hpo_id\")]\n   \nrecurrent_infections_ids <- KGExplorer::get_ontology_descendants(ont = hpo,\n                                                                 terms = \"Recurrent infections\")[[1]]\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRecurrent infections\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhepatoblast_res <- results[q<0.05 &hpo_id %in% recurrent_infections_ids & cl_name==\"hepatoblast\"]\nhepatocyte_res <- results[q<0.05 & ancestor_name==\"Abnormality of the immune system\" & grepl(\"hepatocyte\",CellType,ignore.case = TRUE)] \n```\n:::\n\n\n\nWe selected the HPO term 'Recurrent bacterial infections' and all of its descendants (19 phenotypes) as an example of how investigations at the level of granular phenotypes can reveal different cell type-specific mechanisms ([Fig. @fig-rni]). As expected, these phenotypes are primarily associated with immune cell types (e.g. macrophages, dendritic cells, T cells, monocytes, neutrophils). Some associations confirm relationships previously suggested in the literature, such as that between 'Recurrent staphylococcal infections' and myeloid cells [@Heim2014-du; @Pidwill2020-le; @Stoll2018-dc; @Tebartz2015-xs]. Specifically, our results pinpoint monocytes as the most strongly associated cell subtypes ($FDR_{p,c}= 1.03e-30,B= 1.76e-01$).\n\nIn contrast to all other recurrent infection types, 'Recurrent Neisserial infections' highlighted a novel association with hepatoblasts (Descartes Human : $FDR_{p,c}= 1.13e-06,B= 8.24e-02$). Whilst unexpected, a convincing explanation involves the complement system, a key driver of innate immune response to Neisserial infections. Hepatocytes, which derive from hepatoblasts, produce the majority of complement proteins [@Zhou2016-kq], and Kupffer cells express complement receptors @Dixon2013-ok. In addition, individuals with deficits in complement are at high risk for Neisserial infections [@Ladhani2019-nf; @Rosain2017-ih], and a genome-wide association study in those with a Neisserial infection identified risk variants within complement proteins [@The_International_Meningococcal_Genetics_Consortium2010-if] . While the potential of therapeutically targeting complement in RDs (including Neisserial infections) has been proposed previously [@Lung2019-il; @Reis2015-yz], performing this in a gene- and cell type-specific manner may help to improve efficacy and reduce toxicity (e.g. due to off-target effects). Importantly, there are over 56 known genes within the complement system [@Seal2023-pa], highlighting the need for a systematic, evidence-based approach to identify effective gene targets.\n\nAlso of note, despite the fact that our datasets contain both hepatoblasts and their mature counterpart, hepatocytes, only the hepatoblasts showed this association. This suggests that the genetic factors that predispose individuals for risk of Neisserial infections are specifically affecting hepatoblasts before they become fully differentiated. It is also notable that these phenotypes were the only ones within the 'Recurrent bacterial infections' branch, or even the broader 'Recurrent infections' branch, perhaps indicating a unique role for hepatoblasts in recurrent infectious disease. The only phenotypes within the even broader 'Abnormality of the immune system' HPO branch that significantly associated with mature hepatocytes were 'Pancreatitis' ($FDR_{p,c}= 2.08e-02,B= 5.25e-02$) and 'Susceptibility to chickenpox' ($FDR_{p,c}= 1.20e-02,B= 5.49e-02$) both of which are well-known to involve the liver [@Al-Hamoudi2009-le; @Brewer2018-dg; @Eshchar1973-tz].\n\n\n\n::: {#cell-fig-rni .cell}\n\n```{.r .cell-code .hidden}\ninfections_out$plot + \n  ggplot2::guides(fill=ggplot2::guide_legend(ncol=2,\n                                             title = NULL))\n```\n\n::: {.cell-output-display}\n![Hepatoblasts have a unique role in recurrent Neisserial infections. Significant phenotype-cell type tests for phenotypes within the branch 'Recurrent bacterial infections'. Amongst all different kinds of recurrent bacterial infections, hepatoblasts (highlighted by vertical dotted lines) are exclusively enriched in 'Recurrent gram−negative bacterial infections'. Note that terms from multiple levels of the same ontology branch are shown as separate facets (e.g. 'Recurrent bacterial infections' and 'Recurrent gram−negative bacterial infections').](index_files/figure-docx/fig-rni-1.png){#fig-rni}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Annotate results with disease/symptom-level and gene-level information\n## filtering q-values at this step yields the same results as filtering at the next step, \n## albeit with much fast computation.\nresults_annot <- HPOExplorer::add_genes(results[q<0.05],\n                                        allow.cartesian = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nresults_annot <- MSTExplorer::add_symptom_results(results = results_annot, \n                                                  ctd_list = ctd_list)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding symptom-level results.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSubsetting results by q_threshold and effect.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,301,874 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## Plot multi-scale mechanisms as an interactive network\nphenotype <- \"Recurrent Neisserial infections\"\nvn_rni <- MSTExplorer::prioritise_targets_network(\n  top_targets = results_annot[hpo_name==phenotype], \n  main = NULL,  \n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: visNetwork\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//Rtmp3HWyxH/filee16024049b8d_prioritise_targets_network.html\n```\n\n\n:::\n:::\n\n\n\nNext, we sought to link multi-scale mechanisms at the levels of disease, phenotype, cell type, and gene and visualise these as a network ([Fig. @fig-network-rni]). This revealed that genetic deficiencies in different complement system genes (*C5*, *C8*, and *C7*) are primarily mediated by different cell types (hepatoblasts, stratified epithelial cells, and stromal cells, respectively). While genes of the complement system are expressed throughout many different tissues and cell types, these results indicate that different subsets of these genes may mediate their effects through different cell types. This finding suggests that investigating (during diagnosis) and targeting (during treatment) different cell types may be critical for the diagnosis and treatment of these closely related, yet mechanistically distinct, diseases.\n\n::: {#fig-network-rni .content-visible unless-format=\"html\"}\n![](img/fig-rni.png)\n:::\n\n::: {.content-hidden unless-format=\"html\"}\n\n\n::: {#cell-fig-network-rni .cell}\n\n```{.r .cell-code .hidden}\nvn_rni$plot\n```\n\n![Multi-scale mechanisms of Recurrent Neisserial infections. Starting from the bottom of the plot, one can trace how causal genes (yellow boxes) mediate their effects through cell types (orange circles), phenotypes (pruple cylinders) and ultimately diseases (blue cylinders). Cell types are connected to phenotypes via association testing ($FDR_{p,c}<0.05$), and to diseases when the symptom gene set overlap is >25%. Nodes were spatially arranged using the Sugiyama algorithm [@Sugiyama1981-ev].](index_files/figure-docx/fig-network-rni-1.png){#fig-network-rni}\n:::\n\n\n:::\n\n### Monarch Knowledge Graph recall\n\nNext, we used the Monarch Knowledge Graph (MKG) as a proxy for the field's current state of knowledge of phenotype-cell type associations. We evaluated the proportion of MKG associations that were recapitulation by our results. In total, our results contained at least one significant cell type associations for \\>90% of the phenotypes described in the MKG. Of these phenotypes, we captured \\>45% of the MKG phenotype-cell associations when only considering exact overlap of CL-aligned cell type annotations. This proportion increased with greater flexibility in the matching of cell type annotations, reaching a maximum of `**!!RECOMPUTE!!**`% at a ontology graph distance of `**!!RECOMPUTE!!**` when considering the overlap of cell type annotations at the level of cell type ontology terms. This suggests that our results are in line with the current state of knowledge, and that our approach can be used to identify novel phenotype-cell type associations.\n\n### Annotation of phenotypes using generative large language models\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ngpt_check <- HPOExplorer::gpt_annot_check()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n151 phenotypes do not have matching HPO IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading in GPT annotations for 16,982 phenotypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNumber of phenotype hits per query group:\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n - intellectual_disability: 6\n - impaired_mobility: 292\n - physical_malformations: 78\n - blindness: 1\n - sensory_impairments: 252\n - immunodeficiency: 5\n - cancer: 695\n - reduced_fertility: 5\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: The `facets` argument of `facet_grid()` is deprecated as of ggplot2 2.2.0.\nℹ Please use the `rows` argument instead.\nℹ The deprecated feature was likely used in the HPOExplorer package.\n  Please report the issue at\n  <https://github.com/neurogenomics/HPOExplorer/issues>.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngpt_annot <- HPOExplorer::gpt_annot_codify()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n151 phenotypes do not have matching HPO IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading in GPT annotations for 16,982 phenotypes.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngpt_annot$annot_weighted[,hpo_name:=gsub(\"^obsolete \",\"\",hpo_name)]\nleast_severe_phenotype <- gpt_annot$annot_weighted[hpo_name==\"Thin toenail\" & severity_score_gpt==0,]\n```\n:::\n\n\n\nSeverity annotations were gathered from GPT-4 for 16982/18082 (93.9166%) HPO phenotypes. In our companion study, benchmarking tests of these results using ground-truth HPO branch annotations. For example, phenotypes within the 'Blindness' HPO branch (*HP:0000618*) were correctly annotated as causing blindness by GPT-4. Across all annotations, the recall rate of GPT-4 annotations was 91.26% (min=70.1%, max=100%, SD=11.84) with a mean consistency score of 91.21% (min=80.96%, max=97.48%, SD=5.739) for phenotypes whose annotation were collected more than once. This clearly demonstrates the ability of GPT-4 to accurately annotate phenotypes. This allowed us to begin using these annotations to compute systematically collected severity scores for all phenotypes in the HPO.\n\nFrom these annotations we computed a weighted severity score metric for each phenotype ranging from 0-100 (100 being the theoretical maximum severity of a phenotype that always causes every annotation). Within our annotations, the most severe phenotype was 'Anencephaly' (*HP:0002323*) with a severity score of 58, followed by 'Atrophy/Degeneration affecting the central nervous system' (*HP:0007367*) with a severity score of 58. There were 677 phenotypes with a severity score of 0 (e.g. 'Thin toenail'). The mean severity score across all phenotypes was 14.89 (median=14, standard deviation=8.517).\n\n### Enrichment of foetal cell types in congenital phenotypes\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nplot_congenital_annotations_out <- MSTExplorer::plot_congenital_annotations(\n  results = results)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n151 phenotypes do not have matching HPO IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading in GPT annotations for 16,982 phenotypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot_congenital_annotations_out_data <- \n  data.table::data.table(plot_congenital_annotations_out$data, key=\"congenital_onset\")\nplot_congenital_annotations_out_data[,summary:=paste0(\n  shQuote(congenital_onset),\"=\",.label,\n  \" (n=\",counts,\" associations)\"\n)]\nplot_congenital_annotations_out_stats <- data.table::data.table(\n  plot_congenital_annotations_out$data_stats$summary_data\n  )[,summary:=paste0(\n  \"$\",\n  \"p=\",format(p.value,digits=2),\",\",\n  \"\\\\chi^2_{Pearson}=\",format(statistic,digits=2),\",\",\n  \"\\\\hat{V}_{Cramer}=\",format(estimate,digits=2),\n  \"$\"\n)]\n```\n:::\n\n\n\nThe frequency of congenital onset with each phenotype (as determined by GPT-4 annotations) was strongly predictive with the proportion of significantly associated foetal cell types in our results ($p=2e-203,\\chi^2_{Pearson}=940,\\hat{V}_{Cramer}=0.14$). Furthermore, increasing congenital frequency annotation (on an ordinal scale) corresponded to an increase in the proportion of foetal cell types: 'always'=24% (n=1636 associations), 'often'=20% (n=2979 associations), 'rarely'=12% (n=1956 associations), 'never'=10% (n=811 associations). This is consistent with the expected role of foetal cell types in development and the aetiology of congenital disorders.\n\n\n\n::: {#cell-fig-congenital .cell}\n\n```{.r .cell-code .hidden}\nplot_congenital_annotations_out$plot\n```\n\n::: {.cell-output-display}\n![Congenital phenotypes are more often associated with foetal cell types. As a phenotype is more often congenital in nature, the greater proportion of foetal cell types are significantly asscoaited with it.](index_files/figure-docx/fig-congenital-1.png){#fig-congenital}\n:::\n:::\n\n\n\n### Diagnosis via cell type-specific disease prediction\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Define input phenotypes/genes\nphenotypes_diagnose <- c(\"Generalized neonatal hypotonia\",\n                         \"Scrotal hypospadias\",\n                         \"Increased circulating progesterone\")\nphenotypes_diagnose <- HPOExplorer::map_phenotypes(phenotypes_diagnose,\n                                                   to=\"id\",\n                                                   hpo=hpo)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngenes_include <- c(\"HSD3B2\",\"HERC2\")\ngenes_exclude <- c(\"SNORD115-1\")\n## Predict cell types\npredict_celltypes_out <- MSTExplorer::predict_celltypes(\n  phenotypes = names(phenotypes_diagnose),\n  genes_include = genes_include, \n  genes_exclude = genes_exclude,\n  phenotype_to_genes = p2g,\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding logFC column.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMapping cell types to cell ontology terms.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding stage information.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_DescartesHuman.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_HumanCellLandscape.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating gene-disease associations with Evidence Score\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning: Invalid .internal.selfref detected and fixed by taking a (shallow)\ncopy of the data.table so that := can add this new column by reference. At an\nearlier point, this data.table has been copied by R (or was created manually\nusing structure() or similar). Avoid names<- and attr<- which in R currently\n(and oddly) may copy the whole data.table. Use set* syntax instead to avoid\ncopying: ?set, ?setnames and ?setattr. If this message doesn't help, please\nreport your use case to the data.table issue tracker so the root cause can be\nfixed or this message improved.\n```\n\n\n:::\n:::\n\n\n\nUsing the function `MSTExplorer::predict_celltypes` we input 3 inclusion phenotypes ('Generalized neonatal hypotonia' (*HP:0008935*), 'Scrotal hypospadias' (*HP:0012853*), 'Increased circulating progesterone' (*HP:0031216*)), 2 genes in which the patient is known to have deleterious mutations (*HSD3B2*, *HERC2*) and 1 gene in which the patient is known not to have any deleterious mutations (*SNORD115-1*). This predicted that cortical cell of adrenal gland (score sum=1.38, score mean=0.0256, score standard deviation=0.137) were the most probable cell types underlying this combination of phenotypes and genotypes ([Fig. @fig-diagnosis]), which is highly consistent with existing evidence that adrenal insufficiency can cause both phenotypes via mutations in these genes [@Srivastava2023-ge; @Utsch2004-re]. This was the only cell type to receive a score two standard deviations from the mean score of all cell types (mean score: 0.000668).\n\n\n\n::: {#cell-fig-diagnosis .cell}\n\n```{.r .cell-code .hidden}\npredict_celltypes_out$plot\n```\n\n::: {.cell-output-display}\n![Diagnosis - Observed phenotypes/genotypes can be used to identify causal cell types in individuals. Our phenotype-cell type association results can be used to make predictions about which cell types are underlying a set of phenotypes observed in a given patient. Here we input three inclusion phenotypes, two inclusion genes, and one exclusion gene into the function `MSTExplorer::predict_celltypes`. The output is a ranked list of the top 10 most probable cell types (*x-axis*) underlying this combination of phenotypes/genotypes (highest to lowest rank from left to right). The score on the *y-axis* is computed by aggregating phenotype-celltype association summary statistics and evidence-weighted phenotype-gene associations. In this simple example, cortical cells of the adrenal gland were predicted as the most probable cell type. The mean of the score sum is shown as a dashed line, while one standard deviation (SD) above this is shown as a dotted line. Each bar is coloured by its mean.](index_files/figure-docx/fig-diagnosis-1.png){#fig-diagnosis}\n:::\n:::\n\n\n\n### Prognosis via cell type-mediated differential outcomes\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Count number of diseases associated with these phenotypes\nkeep_descendants <- \"Hypotonia\" ## HP:0001252\nhypotonia_results <- HPOExplorer::filter_descendants(results, \n                                                     keep_descendants = keep_descendants) \n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nKeeping descendants of 1 term(s).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n14 terms remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n2,814 associations remain after filtering.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhypotonia_results <- HPOExplorer::add_death(hypotonia_results,\n                                            allow.cartesian = TRUE,\n                                            agg_by = c(\"disease_id\",\"hpo_id\"))\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with AgeOfDeath.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nhypotonia_results <- MSTExplorer::map_celltype(hypotonia_results) \n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## Generate plot\nplot_differential_outcomes_heatmap_out <- MSTExplorer::plot_differential_outcomes_heatmap( \n  results = hypotonia_results, \n  print_phenotypes = TRUE,\n  fill_limits = c(1,8),\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding symptom-level results.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSubsetting results by q_threshold and effect.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n52,234 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_DescartesHuman.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading ctd_HumanCellLandscape.rds\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmin_ageofdeath_score_celltypes <- unique(plot_differential_outcomes_heatmap_out$data_agg[which(AgeOfDeath_score_min==min(AgeOfDeath_score_min))]$celltype_symptom)\n```\n:::\n\n\n\nHypotonia (*HP:0001252*) is a very broad phenotype containing 13 subterms (e.g. \"Generalised neonatal hypotonia\") and is associated with 2569 unique diseases in the HPO gene annotations. Together, these hypotonia phenotypes were significantly associated with 29/99 (29.29%) unique CL-aligned cell types. This reflects the highly variable set of disease etiologies that can cause this broad-level phenotype. Across all diseases, hypotonia phenotypes tended to be most consistently severe (lower mean age of death score) when associated with the cell type inhibitory interneuron. While other cell types were associated with lower mean age of death scores (e.g. stromal cell, astrocyte), the severity of the outcomes were more variable.\n\n\n\n::: {#cell-fig-prognosis .cell}\n\n```{.r .cell-code .hidden}\nplot_differential_outcomes_heatmap_out$plot\n```\n\n::: {.cell-output-display}\n![Prognosis - Cell types predict the probability of deadly diseases. The broad phenotype 'Hypotonia' and its descendants occur in many different diseases (1,832 diseases in the HPO annotations).Therefore, it can be difficult to prognose clinical outcomes of a newborn individual with hypotonia. With additional knowledge of the particular cell types underlying a patient's hypotonia phenotype, one can greatly narrow down the range of potential outcomes (e.g. age of death). **a**, Here, we show the various cell types by which hypotonia phenotypes confer disease risk. **b**, We also computed the mean age of death score for each cell type across hypotonia-associated diseases, revealing that disrupted inhibitory neurons confer the greatest risk of early death. Ordinal age of death categories from the HPO disease annotations were encoded numerically and averaged ([Table @tbl-death]) to produce mean Age of Death scores for each disease (on a scale from 1-8). For example, a score of 1 corresponds to prenatal death, while a score of 8 corresponds to death in late adulthood.](index_files/figure-docx/fig-prognosis-1.png){#fig-prognosis}\n:::\n:::\n\n\n\n### Therapeutic target identification\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nprioritise_targets_out <- MSTExplorer::prioritise_targets(\n  results = results, \n  ctd_list = ctd_list,\n  phenotype_to_genes = p2g,\n  hpo = hpo,\n  \n  keep_deaths=NULL,\n  keep_onsets=NULL,\n  keep_specificity_quantiles = seq(30,40), ## NULL:70, 30-40:64 \n  keep_mean_exp_quantiles = seq(30,40), ## NULL:65, 10:55\n  info_content_threshold=8, ## 8:55, 5:64 \n  effect_threshold=NULL, ## 1:39\n  severity_score_gpt_threshold=NULL, ## 10:78, NULL:82\n  symptom_intersection_threshold=.25, ## .25:57\n  evidence_score_threshold=3,  ## 5:47, 4:47, 3:64\n  top_n = 10, ## 5:38, 20:42, 30:45, 40:52, 50:55\n  group_vars = \"hpo_id\")\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritising gene targets.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding term definitions.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding information_content scores.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='start' \n - Rows: 51,874,984 \n - Phenotypes: 11,028 \n - Diseases: 12,467 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltering @ q-value <= 0.05\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='q_threshold' \n - Rows: 2,115,670 \n - Phenotypes: 9,575 \n - Diseases: 12,467 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='effect_threshold' \n - Rows: 2,115,670 \n - Phenotypes: 9,575 \n - Diseases: 12,467 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with AgeOfDeath.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_deaths' \n - Rows: 2,115,670 \n - Phenotypes: 9,575 \n - Diseases: 12,467 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAncestor columns already present. Skipping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nKeeping descendants of 1 term(s).\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n17,548 terms remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n1,889,042 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_descendants' \n - Rows: 1,889,042 \n - Phenotypes: 9,499 \n - Diseases: 12,364 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_ont_levels' \n - Rows: 1,889,042 \n - Phenotypes: 9,499 \n - Diseases: 12,364 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nTranslating ontology terms to ids.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n151 phenotypes do not have matching HPO IDs.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading in GPT annotations for 16,982 phenotypes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='gpt_filters' \n - Rows: 1,889,042 \n - Phenotypes: 9,499 \n - Diseases: 12,364 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='severity_score_gpt_threshold' \n - Rows: 1,889,042 \n - Phenotypes: 9,499 \n - Diseases: 12,364 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='info_content_threshold' \n - Rows: 979,360 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with onset.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_onsets' \n - Rows: 979,360 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Tiers.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_tiers' \n - Rows: 979,360 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with modifiers\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='severity_threshold' \n - Rows: 979,435 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='severity_threshold_max' \n - Rows: 979,435 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with n_diseases\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: genes_to_phenotype.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='pheno_ndiseases_threshold' \n - Rows: 979,435 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenotype frequencies.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='pheno_frequency_threshold' \n - Rows: 981,649 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_celltypes' \n - Rows: 981,649 \n - Phenotypes: 7,691 \n - Diseases: 11,916 \n - Cell types: 201\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nConverting phenos to GRanges.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: ensembldb\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering metadata for 4926 unique genes.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: EnsDb.Hsapiens.v75\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='symptom_gene_overlap' \n - Rows: 1,092,098 \n - Phenotypes: 7,015 \n - Diseases: 8,102 \n - Cell types: 201 \n - Genes: 4,650\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltering by keep_chr.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_chr' \n - Rows: 1,092,098 \n - Phenotypes: 7,015 \n - Diseases: 8,102 \n - Cell types: 201 \n - Genes: 4,650\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltering by gene-disease association evidence.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating gene-disease associations with Evidence Score\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='evidence_score_threshold' \n - Rows: 825,255 \n - Phenotypes: 6,605 \n - Diseases: 6,622 \n - Cell types: 201 \n - Genes: 3,938\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltering by gene size.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n3,938 / 3,938 genes kept.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='gene_size' \n - Rows: 825,255 \n - Phenotypes: 6,605 \n - Diseases: 6,622 \n - Cell types: 201 \n - Genes: 3,938\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='keep_biotypes' \n - Rows: 825,255 \n - Phenotypes: 6,605 \n - Diseases: 6,622 \n - Cell types: 201 \n - Genes: 3,938\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='add_driver_genes' \n - Rows: 255,497 \n - Phenotypes: 6,447 \n - Diseases: 6,442 \n - Cell types: 201 \n - Genes: 3,873\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding symptom-level results.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSubsetting results by q_threshold and effect.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n255,497 associations remain after filtering.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='symptom_intersection_threshold' \n - Rows: 255,497 \n - Phenotypes: 6,447 \n - Diseases: 6,442 \n - Cell types: 201 \n - Genes: 3,873\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating gene frequencies.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: genes_to_phenotype.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='gene_frequency_threshold' \n - Rows: 350,367 \n - Phenotypes: 6,447 \n - Diseases: 6,442 \n - Cell types: 201 \n - Genes: 3,873\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPruning ancestors.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n5287 / 6447 terms were kept after pruning.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='prune_ancestors' \n - Rows: 196,856 \n - Phenotypes: 5,287 \n - Diseases: 6,147 \n - Cell types: 201 \n - Genes: 3,774\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSorting rows.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFinding top 10 gene targets per: hpo_id\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='top_n' \n - Rows: 32,735 \n - Phenotypes: 5,287 \n - Diseases: 4,850 \n - Cell types: 201 \n - Genes: 3,180\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nPrioritised targets: step='end' \n - Rows: 32,735 \n - Phenotypes: 5,287 \n - Diseases: 4,850 \n - Cell types: 201 \n - Genes: 3,180\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngenes_per_pheno <- prioritise_targets_out$top_targets[,list(n=data.table::uniqueN(gene_symbol)),by=\"hpo_id\"]\np2g <- HPOExplorer::add_ont_lvl(p2g)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGetting absolute ontology level for 18,082 IDs.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nmin_ont_lvl <- 3\ngenes_per_pheno_all <- p2g[ontLvl>min_ont_lvl,\n                           list(n=data.table::uniqueN(gene_symbol)),by=\"hpo_id\"]\n\n\ntop_celltypes <- prioritise_targets_out$top_targets[,list(\n  np=data.table::uniqueN(hpo_id)),\n  by=\"cl_name\"]|>data.table::setorderv(\"np\",-1)\ntop_ancestors <- prioritise_targets_out$top_targets[,list(\n  np=data.table::uniqueN(hpo_id),\n  nc=data.table::uniqueN(CellType),\n  ng=data.table::uniqueN(gene_symbol)\n  ),\n  by=\"ancestor_name\"]|>\n  data.table::setorderv(\"np\",-1)\n```\n:::\n\n\n\nNext, we identified putative cell type-specific gene targets for several severe disease phenotypes. This yielded putative therapeutic targets for 5287 phenotypes across 4850 diseases in 201 cell types and 3180 genes ([Fig. @fig-therapy-filter]). While this constitutes a large number of genes in total, each phenotype was assigned a median of 2 gene targets (mean=3.29, min=1, max=10). Relative to the number of genes annotations per phenotype in the HPO overall (median=7, mean=61.95, min=1, max=5003) this represents a substantial decrease in the number of candidate target genes, even when excluding high-level phenotypes (HPO level\\>3). It is also important to note that the phenotypes in the prioritised targets list are ranked by their severity, allowing us to distinguish between phenotypes with a high medical urgency (e.g. 'Hydranencephaly') from those with lower medical urgency (e.g. 'Hyperplastic labia majora'). This can be useful for both clinicians, biomedical scientists, and pharmaceutical manufacturers who wish to focus their research efforts on phenotypes with the greatest need for intervention.\n\nAcross all phenotypes, epithelial cell were most commonly implicated (834 phenotypes), followed by stromal cell (627 phenotypes), stromal cell (627 phenotypes), neuron (478 phenotypes), chondrocyte (385 phenotypes), and endothelial cell (363 phenotypes). Grouped by higher-order ontology category, 'Abnormality of the musculoskeletal system' had the greatest number of enriched phenotypes (961 phenotypes, 863 genes), followed by 'Abnormality of the nervous system' (745 phenotypes, 1163 genes), 'Abnormality of head or neck' (545 phenotypes, 997 genes), 'Abnormality of the genitourinary system' (446 phenotypes, 710 genes), and 'Abnormality of the eye' (379 phenotypes, 572 genes).\n\n### Therapeutic target validation\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n## Gene therapy only\nttd_check_out <- MSTExplorer::ttd_check(\n  top_targets=prioritise_targets_out$top_targets, \n  drug_types = \"Gene therapy\",\n  allow.cartesian = TRUE,\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: readxl\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRetrieving all organisms available in gprofiler.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing stored `gprofiler_orgs`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMapping species name: hsapiens\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n1 organism identified from search: hsapiens\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n35,812 / 51,339 (69.76%) genes mapped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNon-failed gene targets enrichment p-value: 0.0104281415165849\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFailed gene targets depletion p-value: 0.364508393285371\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in ggplot2::geom_text(data = unique(dat_sub[, c(\"HIGHEST_STATUS\", : Ignoring unknown aesthetics: fill\nIgnoring unknown aesthetics: fill\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\n## All therapy types\nttd_check_all_out <- MSTExplorer::ttd_check(\n  top_targets=prioritise_targets_out$top_targets,   \n  allow.cartesian = TRUE,\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRetrieving all organisms available in gprofiler.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing stored `gprofiler_orgs`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMapping species name: hsapiens\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n1 organism identified from search: hsapiens\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n35,812 / 51,339 (69.76%) genes mapped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nNon-failed gene targets enrichment p-value: 3.05778572878398e-19\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFailed gene targets depletion p-value: 2.51631585215379e-199\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in ggplot2::geom_text(data = unique(dat_sub[, c(\"HIGHEST_STATUS\", : Ignoring unknown aesthetics: fill\nIgnoring unknown aesthetics: fill\n```\n\n\n:::\n:::\n\n\n\nTo determine whether the genes prioritised by our therapeutic targets pipeline were plausible, we checked what percentage of gene therapy targets we recapitulated. Data on therapeutic approval status was gathered from the Therapeutic Target Database (TTD; release 2024-03-22) [@Liu2011-qd]. Overall, we prioritised 79% of all non-failed existing gene therapy targets. A hypergeometric test confirmed that our prioritised targets were significantly enriched for non-failed gene therapy targets ($p=0.0104$). Importantly, we did not prioritise any of the failed therapeutics (0%), defined as having been terminated or withdrawn from the market. The hypergeometric test for depletion of failed targets did not reach significance ($p=0.365$), but this is to be expected as there was only one failed gene therapy target in the TTD database.\n\nEven when considering therapeutics of any kind ([Fig. @fig-therapy-validate-all]), not just gene therapies, we recapitulated 44% of the non-failed therapeutic targets and 0% of the terminated/withdrawn therapeutic targets (n=1255). Here we found that our prioritised targets were significantly enriched for non-failed therapeutics ($p=3e-19$), and highly significantly depleted for failed therapeutics ($p=3e-199$). This suggests that our multi-scale evidence-based prioritisation pipeline is capable of selectively identifying genes that are likely to be effective therapeutic targets.\n\n\n\n::: {#cell-fig-therapy-validate .cell}\n\n```{.r .cell-code .hidden}\nttd_check_out$plot\n```\n\n::: {.cell-output-display}\n![Therapeutics - Validation of prioritised therapeutic targets. The proportion of existing gene therapy targets (documented in the Therapeutic Target Database) recapitulated by our prioritisation pipeline. Therapetics are stratified by the stage of clinical development they were at during the time of writing.](index_files/figure-docx/fig-therapy-validate-1.png){#fig-therapy-validate}\n:::\n:::\n\n\n\n### Selected example targets\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntop_targets <- prioritise_targets_out$top_targets[,n_genes:=data.table::uniqueN(gene_symbol),\n                                                  by=\"hpo_id\"][n_genes<5 & proportion_driver_genes_symptom>.25]\n\ntop_phenotypes <- unique(top_targets$hpo_name)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nheight <- \"80vh\"\nwidth <- \"100vw\"\nphenotypes_network <- c(\"Lethal skeletal dysplasia\",\n                        \"GM2-ganglioside accumulation\",\n                        \"Alzheimer disease\",\n                        \"Parkinson disease\")\n\nphenotype <- phenotypes_network[1]\nvn_therapy_eg1 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[hpo_name==phenotype], \n  main = NULL,\n  height = height,\n  width = width,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: visNetwork\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpikSDN3/file64b02a8a1a18_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- phenotypes_network[2]\nvn_therapy_eg2 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[hpo_name==phenotype], \n  main = NULL,\n  height = height,\n  width = width,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpikSDN3/file64b02b947655_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- phenotypes_network[3]\nvn_therapy_eg3 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)], \n  main = NULL, \n  height = height,\n  width = width,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpikSDN3/file64b06a5c2716_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- phenotypes_network[4]\nvn_therapy_eg4 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)], \n  main = NULL, \n  height = height,\n  width = width,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpikSDN3/file64b01bfd4fa4_prioritise_targets_network.html\n```\n\n\n:::\n:::\n\n\n\n::: {.content-visible unless-format=\"html\"}\n![](img/fig-therapy-examples-merged.png)\n:::\n\n::: {.content-hidden unless-format=\"html\"}\n\n\n::: {#fig-therapy-examples .cell layout=\"[[1,1], [1], [1]]\"}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg1$plot\n```\n\n![Lethal skeletal dysplasia](index_files/figure-docx/fig-therapy-examples-1.png){#fig-therapy-examples-1}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg2$plot\n```\n\n![GM2-ganglioside accumulation](index_files/figure-docx/fig-therapy-examples-2.png){#fig-therapy-examples-2}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg3$plot\n```\n\n![Alzheimer disease](index_files/figure-docx/fig-therapy-examples-3.png){#fig-therapy-examples-3}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg4$plot\n```\n\n![Parkinson disease](index_files/figure-docx/fig-therapy-examples-4.png){#fig-therapy-examples-4}\n\nExample cell type-specific gene therapy targets for several severe phenotypes and their associated diseases. Each disease (blue cylinders) is connected to its phenotype (purple cylinders) based on well-established clinical observations recorded within the HPO [@Gargano2024-fc]. Phenotypes are connected to cell types (red circles) via association testing between weighted gene sets ($FDR_{p,c}<0.05$). Each cell type is connected to the prioritised gene targets (yellow boxes) based on the driver gene analysis.The thickness of the edges connecting the nodes represent the (mean) fold-change from the bootstrapped enrichment tests. Nodes were spatially arranged using the Sugiyama algorithm [@Sugiyama1981-ev].\n:::\n\n\n:::\n\nFrom our prioritised targets, we selected the following four sets of phenotypes or diseases as examples: 'Lethal skeletal dysplasia', 'GM2-ganglioside accumulation', 'Alzheimer disease', 'Parkinson disease'.\n\nSkeletal dysplasia is a heterogeneous group of over 450 disorders that affect the growth and development of bone and cartilage. This phenotype can be lethal when deficient bone growth leads to the constriction of vital organs such as the lungs. Even after surgical interventions, these complications continue to arise as the child develops. Pharmacological interventions to treat this condition have largely been ineffective. While there are various cell types involved in skeletal system development, our pipeline nominated chondrocytes as the causal cell type underlying the lethal form of this condition. Assuringly, we found that the disease 'Achondrogenesis Type 1B' is caused by the genes *SLC26A2* and *COL2A1* via chondrocytes. We also found that 'Platyspondylic lethal skeletal dysplasia, Torrance type'. Thus, in cases where surgical intervention is insufficient, targeting these genes within chondrocytes may prove a viable long-term solution for children suffering from lethal skeletal dysplasia.\n\nTay-Sachs disease is a devastating disease in which children are born appearing healthy, which gradually degrades leading to death after 3-5 years. The underlying cause is the toxic accumulation of gangliosides in the nervous system due to a loss of the enzyme produced by *HEXA*. While this could in theory be corrected with gene editing technologies, there remain some outstanding challenges. One of which is early detection and diagnosis, before irreversible damage has occurred. Our pipeline implicated extravillous trophoblasts of the placenta in 'GM2-ganglioside accumulation'. While not necessarily a target for gene therapy, checking these cells *in utero* for an absence of *HEXA* may serve as a viable biomarker as these cells normally express the gene at high levels. Early detection of Tay-Sachs disease may lengthen the window of opportunity for therapeutic intervention, especially when genetic sequencing is not available or variants of unknown significance are found within *HEXA*.\n\nAlzheimer disease (AD) is the most common neurodegenerative condition. It is characterised by a set of variably penetrant phenotypes including memory loss, cognitive decline, cerebral proteinopathy. Interestingly, we found that different forms of early onset AD (which are defined by the presence of a specific disease gene) are each associated with different cell types via different phenotypes. For example, AD 3 and AD 4 are primarily associated with cells of the digestive system ('enterocyte', 'gastric goblet cell') and are implied to be responsible for the phenotypes 'Senile plaques', 'Alzheimer disease', 'Parietal hypometabolism in FDG PET', 'Cerebral amyloid angiopathy'. Meanwhile, early-onset autosomal dominant AD and AD 2 are primarily associated with immune cells ('alternatively activated macrophage', 'microglial cell') and are implied to be responsible for the phenotypes 'Neurofibrillary tangles', 'Long-tract signs', 'Finger agnosia', 'Semantic dementia'. This suggests that different forms of AD may be driven by different cell types and phenotypes, which may help explain its variability in onset and clinical presentation.\n\nFinally, Parkinson disease (PD) is characterised by motor symptoms such as tremor, rigidity, and bradykinesia. However there are a number of additional phenotypes associated with the disease that span multiple physiological systems. PD 19a and PD 8 seemed to align most closely with the canonical understanding of PD as a disease of the central nervous system in that they implicated oligodendrocytes and neurons. Though the reference datasets being used in this study were not annotated at sufficient resolution to distinguish between different subtypes of neurons, in particular dopaminergic neurons. PD 19a/8 also suggested that risk variants in *LRRK2* mediate their effects on PD through both myeloid cells and oligodendrocytes by causing gliosis of the substantia nigra. The remaining clusters of PD mechanisms revolved around chondrocytes (PD 20), amacrine cells of the eye (hereditary late-onset PD), and the respiratory/immune system (PD 14). While the diversity in cell type-specific mechanisms is somewhat surprising, it may help to explain the wide variety of cross-system phenotypes frequently observed in PD.\n\nIt should be noted that the HPO only includes gene annotations for the monogenic forms of AD and PD. However it has previously been shown that there is at least partial overlap in their phenotypic and genetic aetiology with respect to their common forms. Thus understanding the monogenic forms of these diseases may shed light onto their more common counterparts.\n\n### Experimental model translatability\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\npheno_map_genes_match <- KGExplorer::map_upheno_data()\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached data: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/pheno_map_genes_match.rds\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\npheno_map_targets <- pheno_map_genes_match[\n  id1 %in% unique(prioritise_targets_out$top_targets$hpo_id)\n  ]|>\n  data.table::setorderv(\"phenotype_genotype_score\",-1)\ntaxa_count <- sort(table(pheno_map_targets$gene_taxon_label2), decreasing = TRUE)\n\npheno_map_targets_severe <- pheno_map_targets[\n  id1 %in% unique(prioritise_targets_out$top_targets[severity_score_gpt>10,]$hpo_id)\n  ]\n\npheno_map_targets_severe[,summary:=paste0(\n  shQuote(object_label1), \n  \" ($SIM_{o,g}=\",round(phenotype_genotype_score,3),\"$)\"\n  )]\n```\n:::\n\n\n\nWe computed interspecies translatability scores using a combination of both ontological ($SIM_{o}$) and genotypic ($SIM_{g}$) similarity relative to each homologous human phenotype and its associated genes [Fig. @fig-animal-models]. In total, we mapped 278 non-human phenotypes (in *Caenorhabditis elegans*, *Danio rerio*, *Mus musculus*, *Rattus norvegicus*) to 849 homologous human phenotypes. Amongst the 5287 phenotype within our prioritised therapy targets, 356 had viable animal models in at least on non-human species. Per species, the number of homologous phenotypes was: *Danio rerio* (n=214), *Mus musculus* (n=152), *Caenorhabditis elegans* (n=35), *Rattus norvegicus* (n=3). Amongst our prioritised targets with a GPT-4 severity score of \\>10, the phenotypes with the greatest animal model similarity were 'Anterior vertebral fusion' ($SIM_{o,g}=0.967$), 'Disc-like vertebral bodies' ($SIM_{o,g}=0.964$), 'Metaphyseal enchondromatosis' ($SIM_{o,g}=0.946$), 'Peripheral retinal avascularization' ($SIM_{o,g}=0.943$), 'Retinal vascular malformation' ($SIM_{o,g}=0.943$).\n\n## Discussion {#sec-discussion}\n\nAcross the 201 cell types and 11,047 RD-associated phenotypes investigated, more than 46,514 significant phenotype-cell type relationships were discovered. The examples we have highlighted above recapitulate well-known relationships, provide additional cellular context to many of these known relationships, and discover novel relationships at multiple biological scales.\n\nInvestigating RDs at the level of phenotypes offers several key advantages. First, the vast majority of RDs only have one associated gene (7671/8631 diseases = 89%). Aggregating gene sets across diseases into phenotype-centric \"buckets\" permits sufficiently well-powered analyses, with an average of \\~76 genes per phenotype (median=7) [see Fig. @fig-diagram]. Second, we hypothesise that these phenotype-level gene sets converge on a limited number of molecular and cellular pathways. Perturbations to these pathways manifest as one or more phenotypes which, when considered together, tend to be clinically diagnosed as a certain disease. Third, RDs are often highly heterogeneous in their clinical presentation across individuals, leading to the creation of an ever increasing number of disease subtypes (some of which only have a single documented case). In contrast, a phenotype-centric approach enables us to more accurately describe a particular individual’s version of a disease without relying on the generation of additional disease subcategories. By characterising an individual’s precise phenotypes over time, we may better understand the underlying biological mechanisms that have caused their condition. However, in order to achieve a truly precision-based approach to clinical care, we must first characterise the molecular and cellular mechanisms that cause the emergence of each phenotype. Here, we provide a highly reproducible framework that enables this at the scale of the entire phenome. This presents an opportunity to design basket trials of patients with different diseases but overlapping phenotypes and cellular mechanisms [@Zanello2023-zd]. It may be especially helpful for complex patients with diagnostically ambiguous sets of phenotypes who would otherwise be excluded from traditional clinical trials [@Diaz-Santiago2020-ep].\n\nIt was paramount to the success of this study to ensure our results were anchored in ground-truth benchmarks, generated falsifiable hypotheses, and rigorously guarded against false-positive associations. Extensive validation using multiple approaches demonstrated that our methodology consistently recapitulates expected phenotype-cell type associations ([Fig. @fig-summary]-[Fig. @fig-congenital]). This was made possible by the existence of comprehensive, structured ontologies for all phenotypes (HPO) and cell types (CL), which provide an abundance of clear and falsifiable hypotheses for which to test our predictions against. Several key examples include 1) strong enrichment of associations between cell types and phenotypes within the same anatomical systems ([Fig. @fig-summary]b-d), 2) a strong relationship between phenotype-specificity and the strength and number of cell type associations ([Fig. @fig-ontology-lvl]), 3) identification of the precise cell subtypes involved in susceptibility to various subtypes of recurrent bacterial infections ([Fig. @fig-rni]), 4) a strong positive correlation between the frequency of congenital onset of a phenotype and the proportion of developmental cell types associated with it ([Fig. @fig-congenital])), and 5) consistent phenotype-cell type associations across multiple independent single-cell datasets ([Fig. @fig-ctd-correlation]). Having validated our phenotype-cell type associations, we then went on to demonstrate how these results may be used in each stage of clinical care: diagnosis ([Fig. @fig-diagnosis]), prognosis ([Fig. @fig-prognosis]), treatment, and therapeutics development ([Fig. @fig-therapy-examples]).\n\nDiagnosis is an essential but challenging step in RD patient care. Additional phenotypes that emerge over time may assist a clinician to reach a more confident disease diagnosis. However many of these phenotypes can have a serious impact on patient quality of life or survival and avoiding them would be far better for patient outcomes. Often times phenotypes alone cannot clearly pinpoint the disease and thus a diagnosis is never reached. Having a more complete understanding of the mechanisms underlying observed phenotypes allows clinicians to far more effectively make predictions about what additional, less obvious phenotypes they should search for to confirm or reject their hypothesis of disease diagnosis (e.g. with imaging or biomarker tests).\n\nConsider the following hypothetical scenario. A clinician observes that a newborn patient has several phenotypes ('Generalized neonatal hypotonia', 'Scrotal hypospadias', 'Increased circulating progesterone'), none of which conclusively point to a single disease diagnosis. Under the strong suspicion that the phenotypes are genetic in origin, the clinician orders whole-genome sequencing (WGS) on the patient as well as the patient’s family. The clinician finds that the patient has a number of putative causal mutations, narrowing down the number of potential diseases from hundreds to just 10. Further narrowing down the possibilities at this stage can be extremely challenging even for expert clinical geneticists. However, additional knowledge of which tissues and cell types are primarily affected allow the clinician to make a series of testable hypotheses that they may begin to investigate. For example, two of the putative diseases are known to cause aberrant splicing events in a gene that is only expressed in adrenocortical cells ([Fig. @fig-diagnosis]), providing justification to order a needle biopsy of the adrenal gland. RNA sequencing is performed on the tissue biopsy and it is discovered that the patient does indeed have high expression of the dysfunctional transcript, confirming the disease diagnosis [@Lord2021-rf]. This opens new avenues for the patient to receive timely and effective treatments for their specific condition, which is important as their version of the disease tends to lead to death in early childhood if left untreated ([Fig. @fig-prognosis]). Fortunately, their diagnosis now qualifies them to participate in a clinical trial of a novel gene therapy with promising preliminary results. Furthermore, it is predicted that this patient would respond especially well to this treatment given that the mechanisms of action of the gene therapy primarily acts on adrenocortical cells ([Fig. @fig-therapy-examples]).\n\nUnfortunately, there are currently only treatments available for less than 5% of RDs [@Halley2022-pd]. Novel technologies including CRISPR, prime editing, antisense oligonucleotides, viral vectors, and/or lipid nanoparticles, have been undergone significant advances in the last several years [@Bueren2023-ma; @Bulaklak2020-ta; @Godbout2023-uo; @Kohn2023-vh; @Zhao2023-qy] and proven remarkable clinical success in an increasing number of clinical applications [@Darrow2019-om; @Mendell2017-kg; @Mueller2017-fz; @Russell2017-dh]. The U.S. Food and Drug Administration (FDA) recently announced an landmark program aimed towards improving the international regulatory framework to take advantage of the evolving gene/cell therapy technologies [@Lu2024-kl] with the aim of bringing dozens more therapies to patients in a substantially shorter timeframe than traditional pharmaceutical product development (typically 5-20 years with a median of 8.3 years) [@Brown2022-ye]. While these technologies have the potential to revolutionise RD medicine, their successful application is dependent on first understanding the mechanisms causing each disease.\n\nTo address this critical gap in knowledge, we used our results to create a reproducible and customisable pipeline to nominate cell type-resolved therapeutic targets ([Fig. @fig-therapy-filter]-[Fig. @fig-therapy-examples]). Targeting cell type-specific mechanisms underlying granular RD phenotypes can improve therapeutic effectiveness by treating the causal root of an individual's conditions [@Bulaklak2020-ta; @Moffat2017-al]. A cell type-specific approach also helps to reduce the number of harmful side effects caused by unintentionally delivering the therapeutic to off-target tissues/cell types (which may induce aberrant gene activity), especially when combined with technologies that can target cell surface antigens (e.g viral vectors) [@Zhou2013-wx]. This has the additional benefit of reducing the minimal effective dose of a therapeutic, which can be both immunogenic and extremely financially costly [@Bueren2023-ma; @Kohn2023-vh; @Nuijten2022-yc; @Thielen2022-ud]. Here, we demonstrate the utility of a high-throughput evidence-based approach to RD therapeutics discovery by highlighting several of the most promising therapeutic candidates. Our pipeline takes into account a myriad of factors, including the strength of the phenotype-cell type associations, symptom-cell type associations, cell type-specificity of causal genes, the severity and frequency of the phenotypes, suitability for gene therapy delivery systems (e.g. recombinant adeno-associated viral vectors (rAAV)), as well as a quantitative analysis of phenotypic and genetic animal model translatability ([Fig. @fig-animal-models]). We validated these candidates by comparing the proportional overlap with gene therapies that are presently in the market or undergoing clinical trials, in which we recovered 79% of all active gene therapies and 0% of failed gene therapies ([Fig. @fig-therapy-validate], [Fig. @fig-therapy-validate-all]). Despite nominating a large number of putative targets, hypergeometric tests confirmed that our targets were strongly enriched for targets of existing therapies that are either approved or currently undergoing clinical trials.\n\nIt should be noted that our study has several key limitations. First, while our cell type datasets are amongst the most comprehensive human scRNA-seq references currently available, they are nevertheless missing certain tissues, cell types (e.g. spermatocytes, oocytes), and life stages (post-natal childhood, senility). It is also possible that we have not captured certain cell state signatures that only occur in disease (e.g. disease-associated microglia \\[**CITATION**\\]). Though we reasoned that using only control cell type signatures would mitigate bias towards any particular disease, and avoid degradation of gene signatures due to loss of function mutations. Second, the collective knowledge of gene-phenotype and gene-disease associations is far from complete and we fully anticipate that these annotations will continue to expand and change well into the future. It is for this reason we designed this study to be easily reproduced within a single containerised script so that we (or others) may rerun it with updated datasets at any point. Finally, causality is notoriously difficult to prove definitively from associative testing alone, and our study is not exempt from this rule. Despite this, there are several reasons to believe that our approach is able to better approximate causal relationships than traditional approaches. First, we did not intentionally preselect any subset of phenotypes or cell types to investigate here. Along with a scaling prestep during linear modelling, this means that all the results are internally consistent and can be directly compared to one another (in stark contrast to literature meta-analyses). Furthermore, for the phenotype gene signatures we used expert-curated GenCC annotations [@DiStefano2022-ao; @DiStefano2023-np] to weight the current strength of evidence supporting a causal relationship between each gene and phenotype. This is especially important for phenotypes with large genes lists (thousands of annotations) for which some of the relationships may be tenuous. Within the cell type references, we deliberately chose to use specificity scores (rather than raw gene expression) as this normalisation procedure has previously been demonstrated to better distinguish between signatures of highly similar cell types/subtypes [@Skene2016-rb].\n\nMoving forward, we are now actively seeking industry and academic partnerships to begin experimentally validating our multi-scale target predictions and exploring their potential for therapeutic translation. Nevertheless, there are more promising therapeutic targets here than our research group could ever hope to pursue by ourselves. In the interest of accelerating research and ensuring RD patients are able to benefit from this work as quickly as possible, we have decided to publicly release all of the results described in this study. These can be accessed in multiple ways, including through a suite of R packages as well as a web app, the [Rare Disease Celltyping Portal](https://neurogenomics.github.io/rare_disease_celltyping_apps/home/). The latter allows our results to be easily queried, filtered, visualised, and downloaded without any knowledge of programming. Through these resources we aim to make our findings useful to a wide variety of RD stakeholders including subdomain experts, clinicians, advocacy groups, and patients.\n\n## Conclusions {#sec-conclusions}\n\nUltimately, our primary objective was to develop a methodology capable of generating high-throughput phenome-wide predictions while preserving the accuracy and clinical utility typically associated with more narrowly focused studies. With the rapid advancement of gene therapy technologies, and a regulatory landscape that is evolving to better meet the needs of a large and diverse patient population, there is finally momentum to begin to realise the promise of personalised medicine. This has especially important implications for the global RD community which has remained relatively neglected. Here, we lay out the groundwork necessary for this watershed moment by providing a scalable, cost-effective, and fully reproducible means of resolving the multi-scale, cell-type specific mechanisms of virtually all rare diseases.\n\n## Methods {#sec-methods}\n\n### Human Phenotype Ontology\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ngencc <- KGExplorer::get_gencc(agg_by = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\ngencc_version <- KGExplorer::get_version(gencc, return_version = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n:::\n\n\n\nThe latest version of the HPO (release 2024-02-08) was downloaded from the EMBL-EBI Ontology Lookup Service [@Cote2010-gp] and imported into R using the `HPOExplorer` package. This R object was used to extract ontological relationships between phenotypes as well as to assign absolute and relative ontological levels to each phenotype. The latest version of the HPO phenotype-to-gene mappings and phenotype annotations were downloaded from the official HPO GitHub repository and imported into R using `HPOExplorer`. This contains lists of genes associated with phenotypes via particular diseases, formatted as three columns in a table (gene, phenotype, disease).\n\nHowever, not all genes have equally strong evidence of causality with a disease or phenotype, especially when considering that the variety of resources used to generate these annotations (OMIM, Orphanet, DECIPHER) use variable methodologies (e.g. expert-curated review of the medical literature vs. automated text mining of the literature). Therefore we imported data from the Gene Curation Coalition (GenCC) [@DiStefano2022-ao; @DiStefano2023-np], which (as of 2024-03-01) 21798 evidence scores across 7229 diseases and 5142 genes. Evidence scores are defined by GenCC using a standardised ordinal rubric which we then encoded as a semi-quantitative score ranging from 0 (no evidence of disease-gene relationship) to 6 (strongest evidence of disease-gene relationship) (see @tbl-gencc). We then summed evidence scores per disease, merged this table with the HPO disease-phenotype-gene annotation table, and then cast the data into a gene-by-phenotype matrix filled with the aggregated mean evidence score. This can be expressed as the following equations.\n\nLet us denote:\n\n-   $D$ as the set of $d$ diseases.\n\n-   $p$ as a phenotype.\n\n-   $g$ as a gene.\n\nThe final evidence-weighted gene-by-phenotype matrix ($M_{g,p}$) can be expressed as:\n\n::: {#eq-evidence-scores .content-hidden unless-format=\"html\"}\n![](equations/eq1.png){height=\"300px\"}\n\nConstruction of the evidence-weighted gene-by-phenotype matrix.\n:::\n\n\\\n\\\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{=tex}\n\\begin{equation*}\n  \\eqnmarkbox[NavyBlue]{n1}{M_{g,p}}\n  =\n  \\frac{\n    \\eqnmarkbox[Cerulean]{n3a}{\\sum_{d \\in D}}\n    \\eqnmarkbox[blue]{n4a}{R(g,p,d)} \n    \\times \n    \\eqnmarkbox[BlueViolet]{n5}{E(g,d)}  \n  }{\n    \\eqnmarkbox[Cerulean]{n3b}{\\sum_{d \\in D}}\n    \\eqnmarkbox[blue]{n4b}{R(g,p,d)}\n  }\n\\end{equation*}\n\\annotate[yshift=1em]{left}{n1}{Weighted gene-by-phenotype \\\\evidence score matrix} \n\\annotate[yshift=-2em]{below,left}{n3a,n3b}{Iterate over all diseases}\n\\annotate[yshift=-2.5em,xshift=2.5em]{below,right}{n4a,n4b}{Binary gene-by-phenotype \\\\relationship matrix,\\\\ (1=relationship, 0=no relationship)}\n\\annotate[yshift=2em]{left}{n5}{Weighted gene-by-disease \\\\evidence score matrix}\n```\n\n\n:::\n\n\\\n\nHistograms of evidence score distributions at each step in processing can be found in [Fig. @fig-evidence-histograms].\n\n### Single-cell transcriptomic atlases\n\nIn this study, the gene by cell type specificity matrix was constructed using the Descartes Human transcriptome atlas of foetal gene expression, which contains a mixture of single-nucleus and single-cell RNA-seq data (collected with sci-RNA-seq3) [@Cao2020-qz]. This dataset contains 377,456 cells representing 77 distinct cell types across 15 tissues. All 121 human foetal samples ranged from 72 to 129 days in estimated postconceptual age. To independently replicate our findings, we also used the Human Cell Landscape which contains single-cell transcriptomic data (collected with microwell-seq) from embryonic, foetal, and adult human samples across 49 tissues [@Han2020-iq].\n\nSpecificity matrices were generated separately for each transcriptomic atlas using the R package `EWCE` (v1.11.3) [@Skene2016-rb]. Within each atlas, cell types were defined using the authors’ original freeform annotations in order to preserve the granularity of cell subtypes as well as incorporate expert-identified rare cell types. Cell types were only aligned and aggregated to the level of corresponding Cell Ontology (CL) [@Diehl2016-gt] annotations afterwards when generating summary figures and performing cross-atlas analyses. Using the original gene-by-cell count matrices from each single-cell atlas, we computed gene-by-cell type expression specificity matrices as follows.\n\nLet us denote: $g$ as a gene, $c$ as a cell type, and $i$ as a single cell. Genes with very no expression across any cell types were considered to be uninformative and were therefore removed from the input gene-by-cell matrix $F(g,i,c)$.\n\n::: {#eq-ctd-filter .content-hidden unless-format=\"html\"}\n![](equations/eq2.png){height=\"200px\"}\n\nFiltering of the gene-by-cell expression matrices.\n:::\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{=tex}\n\\begin{equation*}\n  \\eqnmarkbox[purple]{f1}{F(g,i,c)}\n  =\n  \\begin{cases}\n  \\eqnmarkbox[WildStrawberry]{f2}{r_{g,i}},\n  \\text{ }l_i = c\\\\0,\n  \\text{ }l_i \\neq c \n  \\end{cases}\n\\end{equation*}\n\\annotate[yshift=1em]{left}{f1}{Filtered gene-by-cell expression matrix} \n\\annotate[yshift=2em]{left}{f2}{Expression of gene $g$ in cell $i$} \n```\n\n\n:::\n\n\\\n\nNext, we calculated the mean expression per cell type and normalised the resulting matrix to transform it into a gene-by-cell type expression specificity matrix ($S_{g,c}$). In other words, each gene in each cell type had a 0-1 score where 1 indicated the gene was mostly specifically expressed in that particular cell type relative to all other cell types. This procedure was repeated separately for each of the single-cell atlases and can be summarised as:\n\n::: {#eq-ctd-specificity .content-hidden unless-format=\"html\"}\n![](equations/eq3.png){height=\"300px\"}\n\nConstruction of the gene-by-cell type specificity matrix.\n:::\n\n\\\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{=tex}\n\\begin{equation*}\n  \\eqnmarkbox[orange]{s1}{S_{g,c}}\n  =\n  \\frac{\n    \\eqnmarkbox[purple]{s3a}{\n      \\frac{\n        \\sum_{i=1}^{|L|} F(g,i,c)\n      }{\n        N_c  \n      }\n    } \n  }{\n   \\eqnmarkbox[OrangeRed]{s6}{\\sum_{r=1}^{k}}(\n     \\eqnmarkbox[purple]{s3b}{\n      \\frac{\n        \\sum_{i=1}^{|L|} F(g,i,c)\n      }{\n        N_c  \n      }\n    } \n   ) \n  }\n\\end{equation*}\n\\annotate[yshift=1em]{left}{s1}{Gene-by-cell type specificity matrix} \n\\annotate[yshift=2em]{left}{s3a,s3b}{Compute mean expression of each gene per cell type} \n\\annotate{below,left}{s6}{Compute row sums of \\\\mean gene-by-cell type matrix}\n```\n\n\n:::\n\n\\\n\n### Phenotype-cell type associations\n\nTo test for relationships between each pairwise combination of phenotype (n=11,047) and cell type (n=201) we ran a series of univariate generalised linear models implemented via the `stats::glm` function in R. First, we filtered the gene-by-phenotype evidence score matrix ($M _{g,p}$) and the gene-by-cell type expression specificity matrix ($S _{g,c}$) to only include genes present in both matrices (n=4,949 genes in the Descartes Human analyses; n=4,653 genes in the Human Cell Landscape analyses). Then, within each matrix any rows or columns with a sum of 0 were removed as these were uninformative data points that did not vary. To improve interpretability of the results $\\beta$ coefficient estimates across models (i.e. effect size), we performed a scaling prestep on all dependent and independent variables. Initial tests showed that this had virtually no impact on the total number of significant results or any of the benchmarking metrics based on p-value thresholds [Fig. @fig-summary]. This scaling prestep improved our ability to rank cell types by the strength of their association with a given phenotype as determined by separate linear models.\n\nWe repeated the aforementioned procedure separately for each of the single-cell references. Once all results were generated using both cell type references (2,206,994 association tests total), we applied Benjamini-Hochberg false discovery rate [@Benjamini1995-vo] (denoted as $FDR_{p,c}$) to account for multiple testing. Of note, we applied this correction across all results at once (as opposed to each single-cell reference separately) to ensure the $FDR_{p,c}$ was stringently controlled for across all tests performed in this study.\n\n### Symptom-cell type associations\n\nHere we define a symptom as a phenotype as it presents within the context of the specific disease. The features of a given symptom can be described as the subset of genes annotated to phenotype $p$ via a particular disease $d$, denoted as $G_{d,p}$ ([see Fig. @fig-diagram]). To attribute our phenotype-level cell type enrichment signatures to specific diseases, we first identified the gene subset that was most strongly driving the phenotype-cell type association by computing the intersect of genes that were both in the phenotype annotation and within the top 25% specificity percentile for the associated cell type. We then computed the intersect between symptom genes ($G_{d,p}$) and driver genes ($G_{p,c}$), resulting in the gene subset $G_{d \\cap p \\cap c}$. Only $G_{d \\cap p \\cap c}$ gene sets with 25% or greater overlap with the symptom gene subset ($G_{d,p}$) were kept. This procedure was repeated for all phenotype-cell type-disease triads, which can be summarised as follows:\n\n::: {#eq-symptoms .content-hidden unless-format=\"html\"}\n![](equations/eq4.png){height=\"300px\"}\n:::\n\n\\\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{=tex}\n\\begin{equation*}\n  \\frac{\n     \\eqnmarkbox[Chartreuse3]{g1}{|G_{d \\cap p \\cap c} |}\n    }{\n       \\eqnmarkbox[Emerald]{g2}{|G_{d,p}|}} \n  \\geq \\eqnmarkbox[SeaGreen]{g3}{.25} \n\\end{equation*}\n\\annotate[yshift=1em]{left}{g1}{Intersect between \\\\symptom genes ($G_{d,p}$) and driver genes ($G_{p,c}$)} \n\\annotate[yshift=-1em]{below,left}{g2}{Symptom genes \\\\(i.e. genes annotated to a phenotype\\\\ via a specific disease)} \n\\annotate[yshift=-1em]{below,right}{g3}{Minimum proportion of overlap \\\\between $G_{d,p,c}$ and $G_{d,p}$}\n```\n\n\n:::\n\n\\\n\n### Validation of expected phenotype-cell type relationships\n\nWe first sought to confirm that our tests (across both single-cell references) were able to recover expected phenotype-cell type relationships across seven high-level branches within the HPO ([Fig. @fig-summary]), including abnormalities of the cardiovascular system, endocrine system, eye, immune system, musculoskeletal system, nervous system, and respiratory system. Within each branch the number of significant tests in a given cell type were plotted ([Fig. @fig-summary]b). Mappings between freeform annotations (the level at which we performed our phenotype- cell type association tests) provided by the original atlas authors and their closest CL term equivalents were provided by CellxGene [@CZI_Single-Cell_Biology_Program2023-fs]. CL terms along the *x-axis* of [Fig. @fig-summary]b were assigned colours corresponding to which HPO branch showed the greatest number of enrichments (after normalising within each branch to account for differences in scale). The normalised colouring allows readers to quickly assess which HPO branch was most often associated with each cell type, while accounting for differences in the number of phenotypes across branches. We then ran a series of Analysis of Variance (ANOVA) tests to determine whether (within a given branch) a given cell type was more often enriched ($FDR_{p,c}<0.05$) within that branch relative to all of the other HPO branches of an equivalent level in the ontology (including all branches not shown in [Fig. @fig-summary]b). After applying Benjamini-Hochberg multiple testing correction [@Benjamini1995-vo] (denoted as $FDR _{b,c}$), we annotated each respective branch-by-cell type bar according to the significance (\\*\\*\\*\\* : $FDR _{b,c}<1e-04$, \\*\\*\\* : $FDR _{b,c}<0.001$, \\*\\* : $FDR _{b,c}<0.01$, \\* : $FDR _{b,c}<0.05$). Cell types in [Fig. @fig-summary]a-b were ordered along the *x-axis* according to a dendrogram derived from the CL ontology ([Fig. @fig-summary]c), which provides ground-truth semantic relationships between all cell types (e.g. different neuronal subtypes are grouped together).\n\nAs an additional measure of the accuracy of our phenotype-cell types test results we identified conceptually matched branches across the HPO and the CL ([Fig. @fig-summary]d and @tbl-celltypes). For example, 'Abnormality of the cardiovascular system' in the HPO was matched with 'cardiocytes' in the CL which includes all cell types specific to the heart. Analogously, 'Abnormality of the nervous system' in the HPO was matched with 'neural cell' in the CL which includes all descendant subtypes of neurons and glia. This cross-ontology matching was repeated for each HPO branch and can be referred to as on-target cell types. Within each branch, the $-log_{10}(FDR _{p,c})$ values of on-target cell types were binned by rounding to the nearest integer (*x-axis*) and the percentage of tests for on-target cell types relative to all cell types were computed at each bin (*y-axis*) ([Fig. @fig-summary]d). The baseline level (dotted horizontal line) illustrates the percentage of on-target cell types relative to the total number of observed cell types. Any percentages above this baseline level represent greater than chance representation of the on-target cell types in the significant tests.\n\n### Monarch Knowledge Graph recall\n\nFinally, we gathered known phenotype-cell type relationships from the Monarch Knowledge Graph (MKG), a comprehensive database of links between many aspects of disease biology [@Putman2024-et]. This currently includes 103 links between HPO phenotypes (n=103) and CL cell types (n=79). Of these, we only considered the 82 phenotypes that we were able to test given that our approach was reliant on gene annotations. We considered instances where we found a significant relationship between exactly matching pairs of HPO-CL terms as a hit.\n\nHowever, as the cell types in MKG were not necessarily annotated at the same level as our single-cell references, we also considered instances where the MKG cell type was an ancestor term of our cell type (e.g. 'myeloid cell' vs. 'monocyte'), or *vice versa*, as hits. Using these criteria, we determined our results recapitulated `**!!RECOMPUTE!!**`% of known phenotype-cell type relationships in the MKG. We next computed how far along the CL ontological tree we would need to travel in order to reach a common ancestor between the MKG cell type and our cell type, for each phenotype-cell type link in the MKG. This provides a metric of not just whether we recapitulated the exact cell types, but how dissimilar our identified cell types were for a given phenotype-cell type association ([Fig. @fig-monarch-recall]).\n\n### Annotation of phenotypes using generative large language models\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ngpt_codes <- formals(HPOExplorer::gpt_annot_codify)\ncode_dict <- paste0(shQuote(names(eval(gpt_codes$code_dict))),\"=\",\n                     eval(gpt_codes$code_dict), collapse = \", \")\ntiers_dict <- paste0(shQuote(names(eval(gpt_codes$tiers_dict))),\"=\",\n                     eval(gpt_codes$tiers_dict), collapse = \", \") \n```\n:::\n\n\n\nOnly a small fraction of the the phenotypes in HPO (\\<1%) have metadata annotations containing information on their time course, consequences, and severity. This is due to the time-consuming nature of manually annotating thousands of phenotypes. To generate such annotations at scale, we used Generative Pre-trained Transformer 4 (GPT-4), a large language model (LLM) as implemented within OpenAI’s chatGPT Application Programming Interface (API). After extensive prompt engineering and ground-truth benchmarking, we were able to acquire annotations on how often each phenotype directly causes intellectual disability, death, impaired mobility, physical malformations, blindness, sensory impairments, immunodeficiency, cancer, reduced fertility, or is associated with a congenital onset. These criteria were previously defined in surveys of medical experts as a means of systematically assessing phenotype severity [@Lazarin2014-we]. Responses for each metric were provided in a consistent one-word format which could be one of: 'never', 'rarely', 'often', 'always'. This procedure was repeated in batches (to avoid exceeding token limits) until annotations were gathered for 16982/18082 HPO phenotypes.\n\nWe then encoded these responses into a semi-quantitative scoring system ('never'=0, 'rarely'=1, 'often'=2, 'always'=3), which were then weighted by multiplying a semi-subjective scoring of the relevance of each metric to the concept of severity on a scale from 1-5, with 5 being the most severe ('intellectual_disability'=5, 'death'=5, 'impaired_mobility'=4, 'physical_malformations'=3, 'blindness'=4, 'sensory_impairments'=3, 'immunodeficiency'=3, 'cancer'=3, 'reduced_fertility'=1, 'congenital_onset'=4). Finally, the product of the score was normalised to a quantitative severity score ranging from 0-100, where 100 is the theoretical maximum severity score. This phenotype severity scoring procedure can be expressed as follows.\n\n::: {#eq-gpt .content-hidden unless-format=\"html\"}\n![](equations/eq5.png){height=\"300px\"}\n\nComputing normalised severity score from encoded GPT-4 annotations.\n:::\n\n\\\n\\\n\n::: {.content-visible unless-format=\"html\"}\n\n\n```{=tex}\n\\begin{equation*}\n  \\eqnmarkbox[Brown4]{nss}{NSS_p}\n  =\n  \\frac{ \n    \\eqnmarkbox[Goldenrod]{nss2}{\\sum_{j=1}^{m}} \n    (\n      \\eqnmarkbox[Goldenrod4]{nss3}{F_{pj}}\n      \\times \n      \\eqnmarkbox[IndianRed4]{nss4}{W_j}\n    )\n    }{\n    \\eqnmarkbox[Tan]{nss5}{\\sum_{j=1}^{m}(\\max\\{F_j\\} \\times W_j)} \n  } \\times 100\n\\end{equation*}\n\\annotate[yshift=1em]{left}{nss}{Normalised Severity Score \\\\for each phenotype}\n\\annotate[yshift=3em]{left}{nss2}{Sum of weighted annotation values \\\\across all metrics}\n\\annotate[yshift=3em]{right}{nss3}{Numerically encoded annotation value \\\\of metric $j$ for phenotype $p$}\n\\annotate[yshift=1em]{right}{nss4}{Weight for metric $j$} \n\\annotate[yshift=-1em]{below,right}{nss5}{Theoretical maximum severity score}\n```\n\n\n:::\n\n\\\n\n### Enrichment of foetal cell types in congenital phenotypes\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nfetal_keywords <- shQuote(eval(formals(MSTExplorer::plot_congenital_annotations)$fetal_keywords) )\n```\n:::\n\n\n\nThe GPT-4 annotations also enabled us to assess whether foetal cell types were more often significantly associated with congenital phenotypes in our Human Cell Landscape results as this single-cell reference contained both adult and foetal versions of cell types ([Fig. @fig-congenital]). To do this, we performed a chi-squared ($\\chi^2$) test on the proportion of significantly associated cell types containing any of the substrings 'fetal', 'fetus', 'primordial', 'hESC' or 'embryonic' (within cell types annotations from the original Human Cell Landscape authors [@Han2020-iq]) vs. those associated without, stratified by how often the corresponding phenotype had a congenital onset according to the GPT phenotype annotations (including 'never', 'rarely', 'often', 'always'). In addition, a series of $\\chi^2$ tests were performed within each congenital onset frequency strata, to determine whether the observed proportion of foetal cell types vs. non-foetal cell types significantly deviated from the proportions expected by chance.\n\n### Diagnosis via cell type-specific disease prediction\n\nWe designed an algorithm that uses our results to predict the most likely cell types underlying a set of phenotypic and genotypic traits observed in a patient ([Fig. @fig-diagnosis]). This is implemented within `MSTExplorer::predict_celltypes` and takes HPO phenotypes as inputs. It can optionally take included risk genes, excluded risk genes, included diseases and/or excluded diseases as additional inputs. It then computes the It then outputs a weighted ranking of cell types, where higher ranking indicates a higher likelihood of being the underlying mechanism of the patient’s particular form of disease(s).\n\n### Prognosis via cell type-mediated differential outcomes\n\nThe phenotype hypotonia is associated with diseases that range in severity from benign to debilitating to fatal [@Ahmed2016-ag]. In the absence of additional information, making an accurate diagnosis is extremely challenging even for experienced physicians. The magnitude of this challenge is highlighted by the fact that each disease is associated with anywhere between 1-595 unique phenotypes (median=61, mean=77.74) within the HPO. Conversely, each phenotype is associated with 1-5404 diseases (median=6, mean=60.74). We addressed this challenge by applying our phenotype-cell type association results in combination with expert-curated HPO annotations of clinical outcomes associated with each phenotype-disease pairing ([Fig. @fig-prognosis]). We first extracted results for the phenotype 'Hypotonia' (*HP:0001252*) and its 13 descendant subterms from our phenotype-cell type association analyses. Next, we encoded the \"Age of Death\" categories associated with each disease in an ordinal scale ranging from 1, corresponding to prenatal death, to 8, corresponding to death in late adulthood (@tbl-death). To determine whether cell type identity significantly predicted the age of death, we conducted an ANOVA where cell type was the predictor and \"Age of Death score\" was the outcome.\n\n### Therapeutic target identification\n\nWe developed a systematic and automated strategy for identifying putative cell type-specific gene targets for each phenotype based on a series of filters at phenotype, cell type, and gene levels. The entire target prioritisation procedure can be replicated with a single function: `MSTExplorer::prioritise_targets`. This function automates all of the reference data gathering (e.g. phenotype metadata, cell type metadata, cell type signature reference, gene lengths, severity tiers) and takes a variety of arguments at each step for greater customisability.\n\n### Therapeutic target validation\n\nTo assess whether our prioritised therapeutic targets were likely to be viable, we computed the overlap between our gene targets and those of existing gene therapies at various stages of clinical development ([Fig. @fig-therapy-validate]). Gene targets were obtained for each therapy from the Therapeutic Target Database (TTD; release 2024-03-22) and mapped onto standardised HUGO Gene Nomenclature Committee (HGNC) gene symbols using the `orthogene` R package. We stratified our overlap metrics according to whether the therapies had failed (unsuccessful clinical trials or withdrawn), or were non-failed (successful or ongoing clinical trials). We then conducted hypergeometric tests to determine whether the observed overlap between our prioritised targets and the non-failed therapy targets was significantly greater than expected by chance (i.e. enrichment). We also conducted a second hypergeometric test to determine whether the observed overlap between our prioritised targets and the failed therapy targets was significantly less than expected by chance (i.e. depletion). Finally, we repeated the analysis against all therapeutic targets, not just those of gene therapies, to determine whether our prioritised targets had relevance to other therapeutic modalities.\n\n### Experimental model translatability\n\nTo improve the likelihood of successful translation between preclinical animal models and human patients, we created an interspecies translatability prediction tool for each phenotype nominated by our gene therapy prioritised pipeline ([Fig. @fig-animal-models]). First, we extracted ontological similarity scores of homologous phenotypes across species from the MKG [@Putman2024-et]. Briefly, the ontological similarity scores ($SIM_o$) are computed for each homologous pair of phenotypes across two ontologies by calculating the overlap in homologous phenotypes that are ancestors or descendants of the target phenotype. Next, we generated genotypic similarity scores ($SIM_g$) for each homologous phenotype pair by computing the proportion of 1:1 orthologous genes using gene annotation from their respective ontologies. Interspecies orthologs were also obtained from the MKG. Finally, both scores are multiplied together to yield a unified ontological-genotypic similarity score ($SIM_{o,g}$).\n\n### Novel R packages\n\nTo facilitate all analyses described in this study and to make them more easily reproducible by others, we created several open-source R packages. [`KGExplorer`](https://github.com/neurogenomics/KGExplorer) imports and analyses large-scale biomedical knowledge graphs and ontologies. [`HPOExplorer`](https://github.com/neurogenomics/HPOExplorer) aids in managing and querying the directed acyclic ontology graph within the HPO. [`MSTExplorer`](https://github.com/neurogenomics/MSTExplorer) facilitates the efficient analysis of many thousands of phenotype-cell type association tests, and provides a suite of multi-scale therapeutic target prioritisation and visualisation functions. These R packages also include various functions for distributing the post-processed results from this study in an organised, tabular format. Of note, `MSTExplorer::load_example_results` loads all summary statistics from our phenotype-cell type tests performed here.\n\n### Rare Disease Celltyping Portal\n\nTo further increase the ease of access for stakeholders in the RD community without the need for programmatic experience, we developed a series of web apps to interactively explore, visualise, and download the results from our study. Collectively, these web apps are called the Rare Disease Celltyping Portal. The landing page for the website was made using HTML, CSS, and javascript and the web apps were created using the Shiny Web application framework for R and deployed on the [shinyapps.io](https://www.shinyapps.io) server. The website can be accessed [here](https://neurogenomics.github.io/rare_disease_celltyping_apps/home). All code used to generate the website can be found [here](https://github.com/neurogenomics/rare_disease_celltyping_apps).\n\n## Data and Code Availability\n\nAll data and code is made freely available through preexisting databases and/or GitHub repositories / software associated with this publication.\n\n-   [Human Phenotype Ontology](https://hpo.jax.org)\n-   [GenCC](https://thegencc.org/)\n-   [Descartes Human scRNA-seq atlas](https://cellxgene.cziscience.com/collections/c114c20f-1ef4-49a5-9c2e-d965787fb90c)\n-   [Human Cell Landscape scRNA-seq atlas](https://cellxgene.cziscience.com/collections/38833785-fac5-48fd-944a-0f62a4c23ed1)\n-   [Rare Disease Celltyping Portal](https://neurogenomics.github.io/rare_disease_celltyping_apps/home)\n-   [`KGExplorer`](https://github.com/neurogenomics/KGExplorer)\n-   [`HPOExplorer`](https://github.com/neurogenomics/HPOExplorer)\n-   [`MSTExplorer`](https://github.com/neurogenomics/MSTExplorer)\n-   [Code to replicate analyses](https://github.com/neurogenomics/rare_disease_celltyping)\n-   [Cell type-specific gene target prioritisation](https://neurogenomics.github.io/RareDiseasePrioritisation/reports/prioritise_targets)\n-   [Complement system gene list](https://www.genenames.org/data/genegroup/#!/group/492)\n\n## Acknowledgements\n\nWe would like to thank the following individuals for their insightful feedback and assistance with data resources: Sarah J. Marzi, Gerton Lunter, Peter Robinson, Melissa Haendel, Ben Coleman, Nico Matentzoglu, Shawn T. O'Neil, Alan E. Murphy, Sarada Gurung.\n\n### Funding\n\nThis work was supported by a UK Dementia Research Institute (UK DRI) Future Leaders Fellowship \\[MR/T04327X/1\\] and the UK DRI which receives its funding from UK DRI Ltd, funded by the UK Medical Research Council, Alzheimer’s Society and Alzheimer's Research UK.\n\n## References {.unnumbered}\n\n::: {#refs}\n\n:::\n\n\\\n\n\n\n{{< pagebreak >}}\n\n\n\n\n\n## Supplementary Materials\n\n### Supplementary Figures\n\n\n\n::: {#cell-fig-evidence-histograms .cell}\n\n```{.r .cell-code .hidden}\nevidence_plot <- HPOExplorer::plot_evidence(phenotype_to_genes = p2g,\n                                            show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating gene-disease associations with Evidence Score\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nConstructing HPO gene x phenotype matrix.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating gene-disease associations with Evidence Score\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAnnotating phenos with Disease\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nGathering data from GenCC.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nImporting cached file.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nEvidence scores for: \n - 10390 diseases \n - 5142 genes\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: 2024-03-01\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nevidence_plot$plot\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Distribution of evidence scores at each processing step.](index_files/figure-docx/fig-evidence-histograms-1.png){#fig-evidence-histograms}\n:::\n:::\n\n\n\n::: {#fig-diagram}\n![](img/fig-diagram.png)\n\nDiagrammatic overview of multi-scale disease investigation strategy. Here we provide an abstract example of differential disease aetiology across multiple scales: diseases ($D$), phenotypes ($P$), cell types ($C$), genes ($G$), and clinical outcomes ($O$). In the HPO, genes are assigned to phenotypes via particular diseases ($G_{d,p}$). Therefore, the final gene list for each phenotype is aggregated from across multiple diseases ($G_{p}$). We performed association tests for all pairwise combinations of cell types and phenotypes and filtered results after multiple testing corrections ($FDR_{p,c}<0.05$). Each phenotype in the context of a given disease is referred to here as a symptom. Links were established between symptoms and cell types through proportional gene set overlap at a minimum threshold of 25%.\n:::\n\n\n\n::: {#fig-ctd-correlation .cell layout-ncol=\"2\"}\n\n```{.r .cell-code .hidden}\nvalidate_associations_correlate_ctd_out$plot$p.all\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_xsidebin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_ysidebin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nvalidate_associations_correlate_ctd_out$plot$logFC.significant\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_xsidebin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_ysidebin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nvalidate_associations_correlate_ctd_out_hcl$plot$p.all\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_xsidebin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_ysidebin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nvalidate_associations_correlate_ctd_out_hcl$plot$logFC.significant\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n`stat_xsidebin()` using `bins = 30`. Pick better value with `binwidth`.\n`stat_ysidebin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![Correlation between the uncorrected p-values from all phenotype-cell type association tests using the Descartes Human vs. Human Cell Landscape CTDs.](index_files/figure-docx/fig-ctd-correlation-1.png){#fig-ctd-correlation-1}\n:::\n\n::: {.cell-output-display}\n![Correlation between the $log_{10}(fold-change)$ from significant phenotype-cell type association tests ($FDR_{p,c}<0.05$) using the Descartes Human vs. Human Cell Landscape CTDs.](index_files/figure-docx/fig-ctd-correlation-2.png){#fig-ctd-correlation-2}\n:::\n\n::: {.cell-output-display}\n![Correlation between the uncorrected p-values from all phenotype-cell type association tests using the Human Cell Landscape fetal samples vs. Human Cell Landscape adult samples.](index_files/figure-docx/fig-ctd-correlation-3.png){#fig-ctd-correlation-3}\n:::\n\n::: {.cell-output-display}\n![Correlation between the $log_{10}(fold-change)$ from significant phenotype-cell type association tests ($FDR_{p,c}<0.05$) using the Human Cell Landscape fetal samples vs. Human Cell Landscape adult samples.](index_files/figure-docx/fig-ctd-correlation-4.png){#fig-ctd-correlation-4}\n:::\n\nInter- and intra-dataset validation across the different CellTypeDataset (CTD) and developmental stages. Correlations are computed using Pearson's correlation coefficient. Point density is plotted using a 2D kernel density estimate.\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n### Generate filtering report plot\nplot_report_out <- MSTExplorer::plot_report(\n  results = results,\n  rep_dt = prioritise_targets_out$report,\n  show_plot = FALSE)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nplot_report:: Preparing data.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype.hpoa\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nReading cached RDS file: phenotype_to_genes.txt\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n+ Version: v2024-02-08\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nplot_report:: Preparing plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot ==> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmppepzlC/file7619591470f2_plot_report.pdf\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving 5 x 4 in image\n```\n\n\n:::\n:::\n\n::: {#cell-fig-therapy-filter .cell}\n\n```{.r .cell-code .hidden}\nplot_report_out\n```\n\n::: {.cell-output-display}\n![Therapeutics - Prioritised target filtering steps. This plot visualises the number of unique phenotype-cell type associations, cell types, genes, and phenotypes (*y-axis*) at each filtering step (*x-axis*) within the multi-scale therapeutic target prioritisation pipeline. Each step in the pipeline can be easily adjusted according to user preference and use case. See **Methods** for descriptions and criterion of each filtering step.**a**, The percentage of phenotypes belonging to each severity Tier after each filtering step (Tier 1 being the most severe). **b**, The number of phenotypes, cell types, associated diseases and genes remaining after each filtering step during the gene prioritisation pipeline.](index_files/figure-docx/fig-therapy-filter-1.png){#fig-therapy-filter}\n:::\n:::\n\n::: {#cell-fig-monarch-recall .cell}\n\n```{.r .cell-code .hidden}\ncat(\"!!!RECOMPUTE!!!\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n!!!RECOMPUTE!!!\n```\n\n\n:::\n:::\n\n::: {#cell-fig-therapy-validate-all .cell}\n\n```{.r .cell-code .hidden}\nttd_check_all_out$plot\n```\n\n::: {.cell-output-display}\n![Therapeutics - Validation of prioritised therapeutic targets. Proportion of existing all therapy targets (documented in the Therapeutic Target Database) recapitulated by our prioritisation pipeline.](index_files/figure-docx/fig-therapy-validate-all-1.png){#fig-therapy-validate-all}\n:::\n:::\n\n::: {#cell-fig-animal-models .cell}\n\n```{.r .cell-code .hidden}\nlibrary(ggplot2) # <-- Necessary due to bug in one of the plotting dependencies \n\ntop_ids <- unique(prioritise_targets_out$top_targets$hpo_id)[seq(1000)]\nplot_upheno_out <- KGExplorer::plot_upheno(\n  pheno_map_genes_match = pheno_map_genes_match, \n  filters=list(id1=top_ids)\n  )\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nFiltered 'id1' : 883 / 987 rows dropped.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n3 / 4 species remain after filtering by `subset_db1`.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: ggdist\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: tidyquant\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'quantmod':\n  method            from\n  as.zoo.data.frame zoo \n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding ancestor metadata.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading cached ontology: /Users/bms20/Library/Caches/org.R-project.R/R/KGExplorer/upheno.rds\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAncestor metadata already present. Use force_new=TRUE to overwrite.\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nplot_upheno_out$heatmap\n```\n\n::: {.cell-output-display}\n![Identification of translatable experimental models. Interspecies translatability of human phenotypes nominated by our gene therapy prioritised pipeline. Above, our combined ontological-genotypic similarity score ($SIM_{o,g}$) is displayed as the heatmap fill colour stratified by the model organism (*x-axis*). An additional column (“n_genes_db1” on the far left) displays the total number of unique genes annotated to the phenotypic within the HPO. Phenotypes are clustered according to their ontological similarity in the HPO (*y-axis*).](index_files/figure-docx/fig-animal-models-1.png){#fig-animal-models}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntop_targets <- prioritise_targets_out$top_targets[,n_genes:=data.table::uniqueN(gene_symbol),\n                                                  by=\"hpo_id\"][n_genes<5 & proportion_driver_genes_symptom>.25]\n\nheight <- \"60vh\"\n\nphenotype <- \"respiratory failure\"\nvn_therapy_eg1 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)],\n  main = phenotype, \n  height = height,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLoading required namespace: visNetwork\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpjIKFEz/file7b98573e1efb_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- \"amyotrophic lateral sclerosis\"\nvn_therapy_eg2 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)],\n  main = phenotype,\n  height = height,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpjIKFEz/file7b9855cbd032_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- \"neurodegeneration\"\nvn_therapy_eg3 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)], \n  main = phenotype, \n  height = height,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpjIKFEz/file7b98271f655a_prioritise_targets_network.html\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nphenotype <- \"small vessel disease\"\nvn_therapy_eg4 <- MSTExplorer::prioritise_targets_network(\n  top_targets = top_targets[grepl(paste(phenotype,collapse = \"|\"), disease_name,ignore.case = TRUE)], \n  main = phenotype, \n  height = height,\n  submain = NULL)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nlogFC already exists in results. Use `force_new=TRUE` to overwrite.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCell type columns already present. Skipping mapping.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating network.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nMaking hoverboxes from: 'node', 'node_type', 'effect', 'q', 'CellType', 'ancestor_name', 'disease_id', 'ontLvl', 'definition', 'hpo_name', 'hpo_id', 'disease_name', 'shape', 'name'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nAdding hoverboxes to data.table.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nCreating visNetwork plot.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n'title' column already exists. Skipping hoverbox creation.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nUsing palette: kovesi.linear_bmy_10_95_c78\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nWarning in\nvisNetwork::visOptions(visNetwork::visInteraction(visNetwork::visEdges(visNetwork::visNodes(visNetwork::visPhysics(visNetwork::visIgraphLayout(visNetwork::toVisNetworkData(g)\n%>% : Can't find 'name' in node data.frame\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nSaving plot --> /var/folders/rd/rbc_wrdj4k3djf3brk6z0_dc0000gp/T//RtmpjIKFEz/file7b984fe634e6_prioritise_targets_network.html\n```\n\n\n:::\n:::\n\n::: {#fig-therapy-examples-supp .cell layout=\"[[1,1], [1], [1]]\"}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg1$plot\n```\n\n![Respiratory failure](index_files/figure-docx/fig-therapy-examples-supp-1.png){#fig-therapy-examples-supp-1}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg2$plot\n```\n\n![Amyotrophic lateral sclerosis](index_files/figure-docx/fig-therapy-examples-supp-2.png){#fig-therapy-examples-supp-2}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg3$plot\n```\n\n![Neurodegeneration](index_files/figure-docx/fig-therapy-examples-supp-3.png){#fig-therapy-examples-supp-3}\n\n```{.r .cell-code .hidden}\nvn_therapy_eg4$plot\n```\n\n![Small vessel disease](index_files/figure-docx/fig-therapy-examples-supp-4.png){#fig-therapy-examples-supp-4}\n\nExample cell type-specific gene therapy targets for several severe phenotypes and their associated diseases. Each disease (blue cylinders) is connected to its phenotype (purple cylinders) based on well-established clinical observations recorded within the HPO [@Gargano2024-fc].Phenotypes are connected to cell types (red circles) via association testing between weighted gene sets ($FDR_{p,c}<0.05$). Each cell type is connected to the prioritised gene targets (yellow boxes) based on the driver gene analysis.The thickness of the edges connecting the nodes represent the (mean) fold-change from the bootstrapped enrichment tests. Nodes were spatially arranged using the Sugiyama algorithm [@Sugiyama1981-ev].\n:::\n\n\n\n### Supplementary Methods\n\n#### Therapeutics: Gene therapy target identification\n\nDescriptions of each step in the prioritisation pipeline are as follows:\n\n1.  **start**: All phenotype-cell type association results.\n\n2.  **q_threshold**: Keep only results that were significant after multiple-testing correction (q\\<0.05).\n\n3.  **fold_threshold**: Keep only results with fold change\\>=1.\n\n4.  **keep_ont_levels**: Keep only phenotypes at certain absolute ontology levels within the HPO.\n\n5.  **keep_onsets**: Keep only phenotypes with postnatal age of onsets to circumvent technical and ethical challenges associated with antenatal gene therapeutics delivery.\n\n6.  **keep_tiers**: Keep only phenotypes with high severity Tiers.\n\n    1.  We used a combination of manual curation and automated text-based substring queries to assign each phenotype a severity Tier as characterised in a survey of healthcare professionals [@Lazarin2014-we].\n\n    2.  Tier 1: Diseases that shortened life span in adolescence or earlier or resulted in intellectual disability.\n\n    3.  Tier 2: Diseases that shortened lifespan prematurely in adulthood, or resulted in impaired mobility or internal physical malformation.\n\n    4.  Tier 3: Diseases causing sensory impairments (hearing, vision, touch, pain, or other), immunodeficiency/cancer, mental illness, or dysmorphic features.\n\n    5.  Tier 4: Diseases that reduce fertility. Of the 49 phenotypes that were available in this severity ranking, we selected three that were classified as Tier 1 (the most severe disease category): mental deterioration, coma and respiratory failure.\n\n7.  **severity_threshold**: Keep only phenotypes with mean severity score equal to or below the threshold.\n\n    1.  Severity scores were computed by assigning each severity modifier term found in the HPO annotations a numerical value. In order of increasing severity:\n\n    2.  HP:0012825 \"Mild\" (Severity_score=4)\n\n    3.  HP:0012827 \"Borderline\" (Severity_score=3)\n\n    4.  HP:0012828 \"Severe\" (Severity_score=2)\n\n    5.  HP:0012829 \"Profound\" (Severity_score=1)\n\n8.  **pheno_frequency_threshold**: Keep only phenotypes with mean frequency equal to or above the threshold (i.e. how frequently a phenotype is associated with any diseases in which it occurs).\n\n    1.  Keep phenotypes with a mean frequency ≥10% or are NA by default.\n\n9.  **keep_celltypes**: Keep only terminally differentiated cell types.\n\n    1.  Of the 77 cell types tested in the Descartes cell type reference, the 40 terminally differentiated cell types were identified through a literature search. Of these, three (extravillous trophoblasts, syncytiotrophoblasts and trophoblast giant cells) were excluded as they only played a role in pregnancy [@Chang2018-qj; @Fogarty2011-ph; @Hu2010-eh], which would raise additional technical and ethical challenges as rAAV therapy has not yet been used to target foetuses in clinical trials.\n\n10. **keep_seqnames**: Remove genes on non-standard chromosomes.\n\n    1.  Only keep chromosomes 1-22, X, and Y.\n\n11. **gene_size**: Keep only genes \\<4.3kb in length.\n\n    1.  Due to limitations in the length of the gene that can be carried by the rAAV vector, genes with a length of \\>4.3kb were excluded.\n\n12. **keep_biotypes**: Keep only genes belonging to certain biotypes (e.g. \"protein_coding\", \"processed_transcript\", \"snRNA\", \"lincRNA\", \"snoRNA\", \"IG_C_gene\").\n\n    1.  Keep all biotypes by default.\n\n13. **gene_frequency_threshold**: Keep only genes at or above a certain mean frequency threshold (i.e. how frequently a gene is associated with a given phenotype when observed within a disease).\n\n    1.  Keep genes with a mean frequency ≥10% or are NA by default.\n\n14. **keep_specificity_quantiles**: Keep only genes in top specificity quantiles from the cell type dataset.\n\n    1.  To further narrow down genes, we extracted relevant metrics from the Descartes reference for each gene in each cell type. These included mean expression, specificity, and specificity quantiles (using 40 bins). Only genes with the most specific quantiles (39-40) were included for further analysis, as cell type-specific genes may be less likely to have off-target effects in other cell types.\n\n15. **keep_mean_exp_quantiles**: Keep only genes in top mean expression quantiles from the cell type dataset\n\n16. **end**: Final table of prioritised cell type- / phenotype-specific gene targets.\n\nFinally, for more comprehensive target search, the we removed the filters for onsets (keep_onsets=NULL), Tier (keep_tiers=NULL), severity (severity_threshold=NULL), as well as relaxed the filters for phenotype frequency threshold (pheno_frequency_threshold=c(10,NA)), gene frequency threshold (gene_frequency_threshold = c(10,NA)), gene specificity quantiles (keep_specificity_quantiles = seq(20,40)), and gene expression quantiles (keep_mean_exp_quantiles = seq(20,40)).\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}