---
title: "Tables" 
format:
  pdf:
    execute:
      cache: true
      echo: false
  docx:
    execute:
      cache: true
      echo: false
---

```{r}
#| label: setup
#| cache: false
library(data.table)
```


```{r tbl-summary}
#| label: tbl-summary 
#| tbl-cap: Summary statistics of enrichment results stratified by single-cell atlas.
#| tbl-subcap: Summary statistics at multiple levels (tests, cell types, phenotypes, diseases, cell types per phenotype, phenotypes per cell type) stratified by the single-cell atlas that was used as a cell type signature reference (Descartes Human or Human Cell Atlas).

data.frame(res_summ$tmerged[,-c("ctd")], 
             row.names = res_summ$tmerged$ctd,
             check.names = FALSE) |>
  t()|>
  knitr::kable()
```

```{r tbl-gencc}
#| label: tbl-gencc 
#| tbl-cap: Encodings for GenCC evidence scores. Assigned numeric values for the GenCC evidence levels.

gencc <- KGExplorer::get_gencc(agg_by=NULL)
dict <- eval(formals(KGExplorer::get_gencc)$dict)
gencc_tbl <- gencc[,list(classification_title=unique(classification_title)),
                   by="classification_curie"][,encoding:=dict[classification_title]]|>
  data.table::setorderv("encoding",-1)
knitr::kable(gencc_tbl)
```

```{r tbl-celltypes}
#| label: tbl-celltypes
#| tbl-cap: On-target cell types for each HPO ancestral branch.

target_branches <- MSTExplorer:::get_target_branches()
target_celltypes <- MSTExplorer:::get_target_celltypes(target_branches=target_branches)
hpo <- HPOExplorer::get_hpo()
celltype_maps <- MSTExplorer::celltype_maps|> data.table::setkeyv("cl_id")

ct_dt <- lapply(names(target_celltypes), function(b){
  cl_ids <- intersect(target_celltypes[[b]],
                      celltype_maps$cl_id) 
  data.table::data.table(hpo_branch=b, 
                         hpo_branch_id=HPOExplorer::map_phenotypes(b,
                                                                   hpo = hpo,
                                                                   to="id"),
                         cl_branch=paste0(target_branches[[b]],collapse=" / "),
                         celltype_maps[cl_ids,c("cl_name","cl_id")])
}) |> data.table::rbindlist(fill=TRUE) |> unique()

knitr::kable(ct_dt)
```

```{r tbl-death, eval=FALSE}
#| label: tbl-death 
#| tbl-cap: Encodings for Age of Death scores. Assigned numeric values for the Age of Death scores within the HPO annotations.
hpo_deaths <- KGExplorer::get_ontology_descendants(ont = hpo,
                                                   include_self = FALSE,
                                                   terms = "Age of death")[[1]]
deaths_dt <- data.table::data.table(hpo_id=hpo_deaths)
deaths_dt <- HPOExplorer::add_hpo_name(deaths_dt)
dict <- HPOExplorer:::hpo_dict(type="AgeOfDeath")
deaths_dt[,encoding:=dict[hpo_name]] |>
  data.table::setorderv("encoding")
knitr::kable(deaths_dt)
```
