---
title: "Identification of cell types underlying thousands of rare diseases and subtraits: manuscript figures"
author: "Kitty B. Murphy, Bobby Gordon-Smith, Jai Chapman, Momoko Otani, Brian M. Schilder, Nathan G. Skene"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(patchwork)
library(ontologyIndex)
library(EWCE)
library(cowplot)
library(wesanderson)
library(dplyr)
library(ggdendro)
library(HPOExplorer)
library(MultiEWCE)
```

```{r load_input_data, echo = FALSE, message = FALSE, warning=FALSE}
setwd("/Volumes/cm1118/projects/neurogenomics-lab/live/Projects/rare_disease_ewce")
hpo <- get_hpo() # keep 
phenotype_to_genes <- load_phenotype_to_genes("data/phenotype_to_genes.txt") 
all_results_merged <- load_example_results()
descartes_mappings <- read.csv("data/DescartesHuman_celltype_mapping.csv") 
descartes_mappings$level1 = gsub("_"," ",descartes_mappings$level1) 
#load("data/ctd_DescartesHuman.rda") 

source("code/phenotypes_per_cell_plot.R")
source("code/ewce_plot_function.R")
```

```{r fig_1_code, echo = FALSE, warning = FALSE, message = FALSE}
### Plot cell type dendrogram - for some reason EWCE::prep_dendro() won't work with the descartes ctd I got from magma.celltyping so I'm running the code line by line instead
ctdIN <- ctd[[1]]
binned_file_dist <- stats::dist(Matrix::t(ctdIN$specificity_quantiles))
binned_file_dist_hclust <- stats::hclust(binned_file_dist)
ddata <- ggdendro::dendro_data(binned_file_dist_hclust,
                               type = "rectangle"
)
ordered_cells <- as.character(ddata$labels$label)
a1 <- ggplot(ggdendro::segment(ddata)) +
  geom_segment(aes_string(x = "x", y = "y", xend = "xend", yend = "yend")) +
  coord_flip() +
  ggdendro::theme_dendro()
a1 <- a1 + scale_x_continuous(expand = c(0, 1.3))
b1 <- ggplot(ggdendro::segment(ddata)) +
  geom_segment(aes_string(x = "x", y = "y", xend = "xend", yend = "yend")) +
  ggdendro::theme_dendro()
b1 <- b1 + scale_x_continuous(expand = c(0, 1.3))
ctdIN$plotting <- list()
ctdIN$plotting$ggdendro_vertical <- a1
ctdIN$plotting$ggdendro_horizontal <- b1
ctdIN$plotting$cell_ordering <- ordered_cells

dendro <- ctdIN$plotting$ggdendro_horizontal +
  scale_x_discrete(breaks = ctd[[1]]$plotting$cell_ordering)

# Extract order of cells in dendrogam and colour code nervous_system, cardiovascular, and immune cell types 
palette_branch <- wesanderson::wes_palette("Darjeeling1")

cell_order <- ctdIN$plotting$cell_ordering
cell_order = gsub("_"," ",cell_order)
nervous_system_cell_types = cell_order[c(6,seq(14,32),41)]
immune_cell_types = cell_order[c(5,6,7,37,59,66,68,75,76,77)]
cardiovascular_cell_types = cell_order[c(4,35,42,38)]
ns_colour = palette_branch[1]; card_colour = palette_branch[2]; immune_colour = palette_branch[3];
cell_colours = c()
for (c in cell_order) {
  if (c %in% nervous_system_cell_types) {
    cell_colours[c] = ns_colour
  } else if (c %in% immune_cell_types) (
    cell_colours[c] = immune_colour
  ) else if (c %in% cardiovascular_cell_types) {
    cell_colours[c] = card_colour
  } else {
    cell_colours[c] = "black"
  }
}

## function to plot the number of significant enrichments per cell type across all branches 
plot_phenos_per_ct <- function(all_results_merged, cell_mappings, fold = 1, q_val = 0.05, dataset = "Descartes")
{
  phenos_per_ct = data.frame()
  for (c in unique(all_results_merged$CellType)) {
    cur_cell = c
    n_phenos = nrow(all_results_merged[all_results_merged$CellType == 
                                           c & all_results_merged$q < q_val & all_results_merged$fold_change > 
                                           fold, "Phenotype"])
    phenos_per_ct = rbind(phenos_per_ct, data.frame(Cell = cur_cell, 
                                                    n_phenos = n_phenos))
  }
  n_pheno_text = phenos_per_ct
  phenos_per_ct$Tissue = rep(NA, length(phenos_per_ct$Cell))
  if (dataset == "Descartes") {
    phenos_per_ct_tissue = data.frame()
    for (i in seq(1:length(phenos_per_ct$Cell))) {
      cur = cell_mappings[cell_mappings$level1 == paste(phenos_per_ct$Cell[i]), 
      ]$tissue
      for (t in unique(cur)) {
        if (!is.na(t)) {
          phenos_per_ct$Tissue[i] = t
          phenos_per_ct_tissue = rbind(phenos_per_ct_tissue, 
                                         phenos_per_ct[i, ])
        }
      }
    }
    
    phenos_per_ct = phenos_per_ct_tissue
  }
  
  for (i in seq(1, length(phenos_per_ct$Cell))) {
    cur = phenos_per_ct[phenos_per_ct$Cell == phenos_per_ct$Cell[i], 
    ]
  }
  
  phenos_per_ct$cell_order <- match(phenos_per_ct$Cell, cell_order)
  phenos_per_ct$Cell <- stats::reorder(phenos_per_ct$Cell, phenos_per_ct$cell_order)
  
  n_pheno_text$Cell <- factor(n_pheno_text$Cell, levels=cell_order)
  
  phenos_per_ct$n_phenos_prop <- "NA"
for(c in unique(phenos_per_ct$Cell)){
  n_phenos <- phenos_per_ct$n_phenos[phenos_per_ct$Cell==c][[1]]
  n_tissues <- length(phenos_per_ct$Tissue[phenos_per_ct$Cell==c])
  prop <- n_phenos/n_tissues
  phenos_per_ct$n_phenos_prop[phenos_per_ct$Cell==c] <- prop
}

phenos_per_ct$n_phenos_prop <- as.numeric(phenos_per_ct$n_phenos_prop)

  
  plot <- ggplot(phenos_per_ct, aes(x=Cell,y=n_phenos_prop)) + 
    scale_y_continuous("", expand = c(0, 0), limits = c(0, max(n_pheno_text$n_phenos) + 55)) + 
    theme_classic() + 
    labs(x="", title= "Number of significant enrichments per cell type") + 
    geom_col(aes(fill = Tissue), size=4, position = "stack") + 
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank(), axis.text.x = element_blank(), 
          axis.ticks.x = element_blank(), plot.title = element_text(hjust = 0.5, size =16), text = element_text(size = 16))
  
  plot_text <- plot + geom_text(data = n_pheno_text, aes(label = n_phenos, y = n_phenos + 20), size = 3) + 
    ylab("Cell type")
  
  return(plot_text)
}

# plot significant phenotypes per celltype across all branches 
phenos_per_ct_plot <- plot_phenos_per_ct(all_results_merged, descartes_mappings)

## function to plot the number of significant enrichments per cell type by branch e.g. abnormality of the nervous system
plot_phenos_per_ct_by_branch <- function(all_results_merged_branch, plot_branches = c("Abnormality of the nervous system", 
                                                                               "Abnormality of the cardiovascular system", "Abnormality of the immune system"), 
                                         q_threshold = 0.05, hpo = hpo, phenotype_to_genes = phenotype_to_genes, 
                                         ctd = ctd, make_dendro = TRUE, palette_branch = c("#FF0000", "#00A08A", "#F2AD00")) 
{

all_results_merged_branch <- all_results_merged

# remove terms not related to 'phenotypic abnormality'
hpo_clinical_mod <- hpo$children["HP:0012823"]
hpo_inheritance <- hpo$children["HP:0000005"]

descendants = list()
for (b in hpo_clinical_mod[[1]]) {
  descendants = ontologyIndex::get_descendants(hpo, b)
  for(d in descendants){
    all_results_merged_branch <- all_results_merged_branch[!grepl(d, all_results_merged_branch$HPO_ID),]
  }
}

descendants = list()
for (b in hpo_inheritance[[1]]) {
  descendants = ontologyIndex::get_descendants(hpo, b)
  for(d in descendants){
    all_results_merged_branch <- all_results_merged_branch[!grepl(d, all_results_merged_branch$HPO_ID),]
  }
}

# get children terms of 'phenotypic abnormality'
hpo_branches = hpo$children["HP:0000118"]
hpo_branches_names = c()
for (b in hpo_branches) {
  hpo_branches_names = c(hpo_branches_names, hpo$name[b])
}
main_branch_df = data.frame(hpo_id = hpo_branches, phenotype = hpo_branches_names)
descendants = list()
for (b in hpo_branches[[1]]) {
  descendants[[hpo$name[b]]] = ontologyIndex::get_descendants(hpo, 
                                                              b)
}

if (!"branch" %in% colnames(all_results_merged_branch)) {
  phenotypes <- unique(all_results_merged_branch$Phenotype)
  
  # remove phenotypes related to age of onset 
  phenotypes <- gsub("^Adult onset$", "", phenotypes)
  phenotypes <- gsub("^Antenatal onset$", "", phenotypes)
  phenotypes <- gsub("^Pediatric onset$", "", phenotypes)
  phenotypes <- gsub("^Congenital onset$", "", phenotypes)
  phenotypes <- gsub("^Neonatal onset$", "", phenotypes)
  phenotypes <- gsub("^Puerpural onset$", "", phenotypes)
  
  phenotypes <- phenotypes[phenotypes != ""]
  
  all_results_merged_branch$branch = NA
  pheno_branches = c()
  for (p in phenotypes) {
    
    hpo_id = unique(all_results_merged_branch$HPO_ID[all_results_merged_branch$Phenotype==p])
    if (!is.na(hpo_id)) {
      id = hpo_id
      for (i in seq(1, length(descendants))) {
        if (id %in% descendants[[i]]) {
          pheno_branches[p] = names(descendants[i])
        }
      }
    }
  }
  
  
  
  for (p in unique(all_results_merged_branch$Phenotype)) {
    all_results_merged_branch$branch[all_results_merged_branch$Phenotype == 
                                p] = pheno_branches[p]
  }
  
  sum <- sum(is.na(all_results_merged_branch$branch))
  
  
  if(sum>0){
    missing_phenos <- phenotypes[phenotypes %in% unique(all_results_merged_branch$Phenotype[is.na(all_results_merged_branch$branch)])]
    missing_phenos <- sub("level", "concentration", missing_phenos)
    meta <- HPOExplorer::hpo_meta
     missing_branches_df <- data.frame(Phenotype=NA, branch=NA)
    for(p in missing_phenos){
      column <- grep(p, meta)
      
      if(length(column)>0 & length(column)<2){
        
        index <- grep(p, meta[[column]])
        alt_id <- meta$HPO_ID[index]
        alt_id <- alt_id[[1]]

      for (i in seq(1, length(descendants))) {
        if (alt_id %in% descendants[[i]]) {
          missing_branches <- data.frame(Phenotype=p, branch=names(descendants[i]))
          missing_branches_df <- rbind(missing_branches_df, missing_branches)
          }
        }
      }
  }
     
     missing_branches_df <- missing_branches_df[-1,]
     unique_key1 <- paste(missing_branches_df$Phenotype)
     unique_key2 <- paste(all_results_merged_branch$Phenotype)
     inds <- is.na(all_results_merged_branch$branch)
     all_results_merged_branch$branch[inds] <- missing_branches_df$branch[match(unique_key2[inds], unique_key1)]
  }
}

# manual fix to branch names
all_results_merged_branch <- all_results_merged_branch[!grepl("Gonosomal inheritance", all_results_merged_branch$Phenotype),]
all_results_merged_branch <- all_results_merged_branch[!grepl("Heterogeneous", all_results_merged_branch$Phenotype),]
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormal circulating insulin level"] <- "Abnormality of the endocrine system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormality of calvarial morphology"] <- "Abnormality of head or neck"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormality of the metacarpal bones"] <- "Abnormality of limbs"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormality of urine glucose concentration"] <- "Abnormality of the genitourinary system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormal echocardiogram"] <- "Abnormality of the cardiovascular system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormality of malar bones"] <- "Abnormality of head or neck"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Abnormality of the periosteum"] <- "Abnormality of the musculoskeletal system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Distal sensory loss of all modalities"] <- "Abnormality of the nervous system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Bilateral external ear deformity"] <- "Abnormality of the ear"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Iron accumulation in globus pallidus"] <- "Abnormality of the nervous system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Marked muscular hypertrophy"] <- "Abnormality of the musculoskeletal system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Decreased pulmonary function"] <- "Abnormality of the respiratory system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Large beaked nose"] <- "Abnormality of the nose"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Dysphasia"] <- "Abnormality of the nervous system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Loss of ability to walk"] <- "Abnormality of the nervous system"
all_results_merged_branch$branch[all_results_merged_branch$Phenotype=="Sparse and thin eyebrow"] <- "Abnormality of head or neck"


  signif_results = all_results_merged_branch[all_results_merged_branch$q <= 
                                        q_threshold & !is.na(all_results_merged_branch$branch), ]
  
n_signif_per_cell_by_branch = data.frame()
for (b in unique(all_results_merged_branch$branch)) {
  for (c in unique(all_results_merged_branch$CellType)) {
    n = length(signif_results[signif_results$CellType == 
                                c & signif_results$branch == b, ]$Phenotype)
    n_signif_per_cell_by_branch = rbind(n_signif_per_cell_by_branch, 
                                        data.frame(branch = b, CellType = c, n_signif = n))
  }
}

n_signif_per_cell_by_branch$hypergeo_p = NA
total_signif = length(signif_results$q)
for (i in seq(1, length(n_signif_per_cell_by_branch$CellType))) {
  cell = n_signif_per_cell_by_branch$CellType[i]
  branch = n_signif_per_cell_by_branch$branch[i]
  group1 = sum(n_signif_per_cell_by_branch$n_signif[n_signif_per_cell_by_branch$CellType == 
                                                      cell])
  group2 = sum(n_signif_per_cell_by_branch$n_signif[n_signif_per_cell_by_branch$branch == 
                                                      branch])
  overlap = sum(n_signif_per_cell_by_branch$n_signif[n_signif_per_cell_by_branch$CellType==cell & 
                                                       n_signif_per_cell_by_branch$branch==branch])
  n_signif_per_cell_by_branch$hypergeo_p[i] = stats::phyper(overlap - 
                                                              1, group2, total_signif - group2, group1, lower.tail = FALSE)
}

  n_signif_per_cell_by_branch$hypergeo_q = stats::p.adjust(n_signif_per_cell_by_branch$hypergeo_p, 
                                                           method = "BH")
  n_signif_per_cell_by_branch$signif_asterisk = ""
  n_signif_per_cell_by_branch$signif_asterisk[n_signif_per_cell_by_branch$hypergeo_q < 
                                                0.05] = "*"
  n_signif_per_cell_by_branch$signif_asterisk[n_signif_per_cell_by_branch$hypergeo_q < 
                                                0.005] = "**"
  n_signif_per_cell_by_branch$signif_asterisk[n_signif_per_cell_by_branch$hypergeo_q < 
                                                5e-04] = "***"
  n_signif_per_cell_by_branch$signif_asterisk[n_signif_per_cell_by_branch$hypergeo_q < 
                                                5e-05] = "****"
  
  n_signif_per_cell_by_branch$cell_order = match(n_signif_per_cell_by_branch$CellType, 
                                                 cell_order)
  n_signif_per_cell_by_branch$CellType = stats::reorder(n_signif_per_cell_by_branch$CellType, 
                                                        n_signif_per_cell_by_branch$cell_order)
  n_signif_per_cell_by_branch$branch_f <- factor(n_signif_per_cell_by_branch$branch, 
                                                 levels = plot_branches)
  
  ns_colour = palette_branch[1]; card_colour = palette_branch[2]; immune_colour = palette_branch[3];
  
  named_colours = c()
  for (i in seq(1, length(plot_branches))) {
    named_colours[plot_branches[i]] = palette_branch[i]
  }
  
  
  facet_branch_plot <- ggplot(n_signif_per_cell_by_branch[n_signif_per_cell_by_branch$branch %in% 
                                                            plot_branches, ], aes(x = CellType, y = n_signif, fill = branch)) + 
    geom_col() + scale_colour_manual(values =  named_colours,aesthetics = "fill") +
    geom_text(mapping = aes(label = signif_asterisk, 
                            y = n_signif + 3)) + cowplot::theme_cowplot() + ylab("Enrichments (n)") + 
    geom_hline(yintercept=0) +
    xlab("Cell type") + theme(axis.text.x = element_text(angle = 90, 
                                                         hjust = 1), legend.position = "none") + 
    facet_wrap(~branch_f,  ncol = 1, scales = "free_y") + #, scales = "free_y") + # <- add back in?
    theme(strip.background = element_rect(colour = "white", fill= "white"),axis.text.x = element_text(colour = cell_colours)) + theme(text = element_text(size = 16)) 
  #scale_y_continuous(expand = c(0,0), limits = c(0,max(n_signif_per_cell_by_branch$n_signif)+6))
  
  return(facet_branch_plot)
}

# plot phenotypes per ct for the abnormality of the nervous system, cardiovascular system, and immune system
phenos_per_ct_branch_plot <- plot_phenos_per_ct_by_branch(all_results_merged, plot_branches = c("Abnormality of the nervous system", 
                                                                                                "Abnormality of the cardiovascular system", "Abnormality of the immune system"), 
                                                          q_threshold = 0.05, hpo = hpo, phenotype_to_genes = phenotype_to_genes, 
                                                          ctd = ctd, palette_branch = c("#FF0000", "#00A08A", "#F2AD00")) 

```


```{r pressure, echo=FALSE}
plot_sig_threshold_prop_enrichments <- function (all_results_merged, hpo, target_cells = c("Excitatory neurons", 
                                                                                                 "Limbic system neurons"), cell_type_description = "nervous_system cells", 
                                                       HPO_Ids = ontologyIndex::get_descendants(hpo, hpo$id[match("Abnormality of the nervous system", 
                                                                                                                  hpo$name)]), phenotype_description = "Nervous system phenotypes", 
                                                       color_pal = c("#619CFF","#F8766D","#00BA38","gray"), color_expected_phenotypes = 1, 
                                                       color_other_phenotypes = 4, blank_x_axis = FALSE) 
{
  cur_descendants_names = c()
  for (d in HPO_Ids) {
    cur_descendants_names = append(cur_descendants_names, 
                                   paste(hpo$name[d]))
  }
  all_results_merged$cur_branch = "Other"
  all_results_merged[all_results_merged$Phenotype %in% cur_descendants_names, 
  ]$cur_branch = phenotype_description
  all_results_merged$cur_branch = factor(all_results_merged$cur_branch)
  all_results_merged$minus_log_p = round(-log10(all_results_merged$p + 
                                                  1e-06), digits = 0)
  proportional_results = data.frame()
  for (logp in unique(all_results_merged$minus_log_p)) {
    cur = all_results_merged[all_results_merged$minus_log_p == 
                               logp, ]
    prop_branch = 100 * (length(cur$cur_branch[cur$cur_branch == 
                                                 phenotype_description & cur$CellType %in% target_cells])/length(cur$cur_branch[cur$CellType %in% 
                                                                                                                                  target_cells]))
    #prop_other = 100 * (length(cur$cur_branch[cur$cur_branch == 
                                               # "Other" & cur$CellType %in% target_cells])/length(cur$cur_branch[cur$CellType %in% 
                                                                                                                   #target_cells]))
    proportional_results = rbind(proportional_results, data.frame(cur_branch = phenotype_description, 
                                                                  prop = prop_branch, minus_log_p = logp))
    #proportional_results = rbind(proportional_results, data.frame(cur_branch = "Other", 
                                                                  #prop = prop_other, minus_log_p = logp))
  }
  #color_pal = wesanderson::wes_palette(wes_color_palette, n_colors)
  cell_type_description <- tolower(cell_type_description)
  prop_plot <- ggplot(proportional_results, aes(x = minus_log_p, 
                                                y = prop, color = cur_branch)) + geom_point(size = 3) + 
    geom_line(mapping = aes(linetype = cur_branch), size = 0.6) + 
    labs(color = "", linetype = "") + ylab(paste0("Enrichments in ", 
                                                  cell_type_description, " (%)")) + 
    scale_y_continuous(limits = c(0, 100)) + cowplot::theme_cowplot() + 
    scale_color_manual(values = c(color_pal[color_expected_phenotypes], 
                                  color_pal[color_other_phenotypes])) + theme(text = element_text(size = 16), legend.position = c(0.15,0.80), title = element_text(size = 16), axis.title.y = element_text(size=16))
  if (! blank_x_axis){
    prop_plot = prop_plot + xlab("-log10(p)")
  } else {
    prop_plot = prop_plot + theme(axis.title.x = element_blank(), axis.ticks.x = element_blank(), axis.text.x = element_blank())
  } 
  return(list(prop_plot, proportional_results))
}

# P value of enrichment against proportion of enrichments in expected cell types
plot_branches = c("Abnormality of the nervous system", "Abnormality of the cardiovascular system", "Abnormality of the immune system")
expected_cells = c("Excitatory neurons", "Cardiomyocytes","Antigen presenting cells")
correlation_results = data.frame()  
proportion_plots = list()
blank_x = c(TRUE, FALSE, TRUE)
for (i in seq(length(plot_branches))) {
  cur_plot <- plot_sig_threshold_prop_enrichments(all_results_merged,
   hpo,
   target_cells=c(expected_cells[i]),
   cell_type_description = expected_cells[i],
   HPO_Ids = ontologyIndex::get_descendants(hpo,hpo$id[match(plot_branches[i],hpo$name)]),
   phenotype_description = plot_branches[i],
   color_pal =  c(palette_branch[1],palette_branch[2],palette_branch[3],"gray"),
   color_expected_phenotypes = i,
   color_other_phenotypes = 4, blank_x_axis = blank_x[i])
  proportion_plots[[i]] = cur_plot[[1]]
  correlation_results = rbind(correlation_results,cur_plot[[2]])
}

sig_threshold_prop_enrichments_plot <- cowplot::plot_grid(plotlist=proportion_plots, align = "h",nrow = 1,labels=c("D","E","F"))

figure_1 <- cowplot::plot_grid(dendro, phenos_per_ct_plot,phenos_per_ct_branch_plot,sig_threshold_prop_enrichments_plot,axis = "lr",
                               align = "v", ncol = 1, rel_heights = c(1, 2, 8,4),labels=c("A","B","C"),label_size = 18)
```

## Figure 1

```{r fig_1_plot, fig.height=22, fig.width = 22, message = FALSE, warning = FALSE, echo = FALSE }

## Plot figure with number of significant enrichments across all branches, for branches of choice, and with dendrogram (Fig. 1 of manuscript)
plot(figure_1)

png('figures/manuscript_fig_1.png', width = 400, height = 400)

print(figure_1)

pdf('figures/manuscript_fig_1.pdf', height=20, width=20)

print(figure_1)

dev.off()
```

```{r fig_2_code, echo = FALSE, warning = FALSE, message = FALSE}
# ontology level plots
blank_x <-   theme(axis.title.x = element_blank())

# get phenotype information for all phenos below 'phenotypic abnormality'
phenos <- make_phenos_dataframe(ancestor="Phenotypic abnormality")
# keep terms which are in the results dataframe
phenos2 <- phenos[phenos$Phenotype %in% all_results_merged$Phenotype]

# ontology level vs number of associated cell types 
n_associated_cells <- c()
for (p in phenos2$Phenotype) {
  n_associated_cells <- append(n_associated_cells, length(all_results_merged$CellType[all_results_merged$Phenotype == p & all_results_merged$q < 0.05 & all_results_merged$fold_change > 1]))
}
phenos2$n_associated_cells <- n_associated_cells
rm(n_associated_cells)

pal <- wesanderson::wes_palette("Darjeeling2", n=2)
ontlvl_ncells_plot <- ggplot(phenos2, mapping=aes(x= factor(ontLvl), y=n_associated_cells)) +
  geom_jitter(color = pal[1], size=1) +
  geom_violin(fill = NA) +
  geom_smooth(color = pal[2], method="loess",mapping = aes(x=ontLvl)) +
  cowplot::theme_cowplot() +
  labs(x="Ontology level", y="Number of associated cell types") +
  blank_x + theme(text = element_text(size = 20),axis.text = element_text(size = 18))  

# ontology level vs fold enrichment
signif_res <- all_results_merged[all_results_merged$q < 0.05,]
signif_res_pheno <- merge(signif_res, phenos2, by="Phenotype")


pal <- wesanderson::wes_palette("Darjeeling2", n=2)
ontlvl_fold_plot <- ggplot(signif_res_pheno, aes(x = factor(ontLvl), y = log10(fold_change))) +
  geom_jitter(color = pal[1], size=1) +
  geom_violin(fill = NA) +
  geom_smooth(color = pal[2], method="loess",mapping = aes(x=ontLvl)) +
  cowplot::theme_cowplot() +
  labs(x="Ontology level", y="log10(fold enrichment)") + 
  theme(text = element_text(size = 20),axis.text = element_text(size = 18)) 


# ontology level vs n of genes
pal <- wesanderson::wes_palette("Darjeeling2", n=2)
ontlvl_ngenes_plot <- ggplot(phenos2, aes(x = factor(ontLvl), y = geneCount)) +
  geom_jitter(color = pal[1], size=1) +
  geom_violin(fill = NA) +
  geom_smooth(color = pal[2], method="loess",mapping = aes(x=ontLvl)) +
  cowplot::theme_cowplot() +
  labs(x="Ontology level", y="Number of associated genes") +
  blank_x + theme(text = element_text(size = 20),axis.text = element_text(size = 18))  

figure_2 <- cowplot::plot_grid(ontlvl_ncells_plot,ontlvl_fold_plot,ontlvl_ngenes_plot,align = "hv",nrow = 1,labels=c("A","B","C"),label_size = 18)
```

## Figure 2

```{r fig_2_plot, fig.height=10, fig.width = 20, message = FALSE, warning = FALSE, echo = FALSE }

## Figure containing ontology level plots (Fig. 2 of manuscript)
plot(figure_2)

png('figures/manuscript_fig_2.png',width = 400, height = 400)

print(figure_2)

pdf('figures/manuscript_fig_2.pdf', height=10, width=20)

print(figure_2)

dev.off()
```


```{r fig_3_code, echo = FALSE, warning = FALSE, message = FALSE}

## Recurrent infections - get results ##
color_pal = wes_palette("Darjeeling1",4)

branch = "Recurrent infections"
branch_id = paste(hpo$id[match(branch,hpo$name)])
branch_descendants = paste(get_descendants(hpo,branch_id))
branch_descendants_names = paste(hpo$name[branch_descendants])
all_results_merged$Phenotype = paste(all_results_merged$Phenotype)
#all_results_merged$cur_branch = paste(all_results_merged$cur_branch)

all_results_merged$cur_branch = paste("Other")
all_results_merged$cur_branch[all_results_merged$Phenotype %in% branch_descendants_names] = branch


branch_signif_counts = data.frame()
for (c in unique(all_results_merged$CellType)) {
  n_signif = length(all_results_merged[all_results_merged$CellType == c & all_results_merged$cur_branch == branch & all_results_merged$q < 0.05, ]$q)
  branch_signif_counts = rbind(branch_signif_counts,
                               data.frame("branch"=branch,
                                          "CellType"=c,
                                          "n_signif"=n_signif))
}

cell_order <- ctdIN$plotting$cell_ordering
cell_order = gsub("_"," ",cell_order)
branch_signif_counts$cell_order = match(branch_signif_counts$CellType, cell_order)
branch_signif_counts$CellType = reorder(branch_signif_counts$CellType, branch_signif_counts$cell_order)
branch_signif_counts$labels = branch_signif_counts$n_signif
branch_signif_counts$labels[branch_signif_counts$labels == 0] = ""

## Recurrent bacterial infections - get results ##
pal <- wesanderson::wes_palette("GrandBudapest2")
branch = "Recurrent bacterial infections"
exclude_root = TRUE

branch_id = paste(hpo$id[match(branch,hpo$name)])
branch_descendants = hpo$children[[branch_id]]
branch_descendants_names = paste(hpo$name[branch_descendants])
if (exclude_root) {
  branch_descendants_names = branch_descendants_names[branch_descendants_names != branch]
} else {
  branch_descendants_names = c(branch, branch_descendants_names)
}
pheno_df = all_results_merged[all_results_merged$Phenotype %in% branch_descendants_names, ]

pheno_df$signif_asterisk = ""
pheno_df$signif_asterisk[pheno_df$q<0.05] = "*"
pheno_df$signif_asterisk[pheno_df$q<0.001] = "**"
pheno_df$signif_asterisk[pheno_df$q<0.0001] = "***"
pheno_df$signif_asterisk[pheno_df$q<0.00001] = "****"

## Recurrent gram-negative bacterial infections - get results ##
pal2 <- append(wesanderson::wes_palette("Darjeeling1"), wesanderson::wes_palette("Darjeeling2")[1])
branch = "Recurrent gram-negative bacterial infections"
exclude_root = TRUE

branch_id = paste(hpo$id[match(branch,hpo$name)])
branch_descendants = hpo$children[[branch_id]]
branch_descendants_names = paste(hpo$name[branch_descendants])
if (exclude_root) {
  branch_descendants_names = branch_descendants_names[branch_descendants_names != branch]
} else {
  branch_descendants_names = c(branch, branch_descendants_names)
}

pheno_df2 = all_results_merged[all_results_merged$Phenotype %in% branch_descendants_names, ]

pheno_df2$signif_asterisk = ""
pheno_df2$signif_asterisk[pheno_df2$q<0.05] = "*"
pheno_df2$signif_asterisk[pheno_df2$q<0.001] = "**"
pheno_df2$signif_asterisk[pheno_df2$q<0.0001] = "***"
pheno_df2$signif_asterisk[pheno_df2$q<0.00001] = "****"

# Get cell types that have fold change > 0 across all results 
branch_signif_counts_cts <- data.frame(CellType=branch_signif_counts$CellType[branch_signif_counts$n_signif>0])
pheno_df_cts <- data.frame(CellType=unique(pheno_df$CellType[pheno_df$fold_change>=1]))
pheno_df2_cts <- data.frame(CellType=unique(pheno_df2$CellType[pheno_df2$fold_change>=1]))
cts_list <- rbind(pheno_df_cts, pheno_df2_cts)
cts_to_subset <- data.frame(CellType=cts_list[!duplicated(cts_list),])

## Recurrent infections - plot ##
branch_signif_counts_subset <- branch_signif_counts[branch_signif_counts$CellType %in% cts_to_subset$CellType,]
recurrent_infections_plot <- ggplot(branch_signif_counts_subset, aes(x=CellType,y=n_signif)) +
    geom_col(fill = color_pal[2], color = "black") +
    geom_text(mapping= aes(label = labels, y = n_signif + 3))+
    theme_cowplot()+
    ylab("Phenotypes (n)") +
    xlab("") +
    scale_y_continuous(expand=c(0,0), limits= c(0,max(branch_signif_counts_subset$n_signif)+5))+
    theme(text = element_text(size = 20), axis.text.x = element_blank(), plot.title = element_text(size=18, hjust = 0.5), axis.ticks.x=element_blank()) +
    ggtitle("Recurrent infections")


## Recurrent bacterial infections - plot ##
pheno_df_subset <- pheno_df[pheno_df$CellType %in% cts_to_subset$CellType,]
pheno_df_subset$cell_order <- match(pheno_df_subset$CellType, cell_order)
pheno_df_subset$CellType = reorder(pheno_df_subset$CellType, pheno_df_subset$cell_order)
recurr_bact_fold_plot <- ggplot(pheno_df_subset, aes(x = CellType, y= fold_change, fill = Phenotype)) +
  geom_col() +
  geom_hline(yintercept=0) +
  geom_text(label = pheno_df_subset$signif_asterisk, mapping = aes(y = fold_change + 1), size=8)+
  theme_cowplot() +
  scale_y_continuous(expand=c(0,0), limits= c(0,max(branch_signif_counts$n_signif)+2))+
  ylab("Fold enrichment") +
  xlab("") +
  theme(text = element_text(size = 20),axis.text.x = element_blank(), plot.title = element_text(size=18, hjust = 0.5), axis.ticks.x=element_blank(), legend.position="none",strip.background = element_blank()) +
  facet_wrap(~Phenotype, ncol=1, scales = "free_y") +
  scale_fill_manual(values = pal) +
  ggtitle("Recurrent bacterial infections child terms")

## Recurrent gram-negative bacterial infection - plot ##
pheno_df2_subset <- pheno_df2[pheno_df2$CellType %in% cts_to_subset$CellType,]
pheno_df2_subset$cell_order <- match(pheno_df2_subset$CellType, cell_order)
pheno_df2_subset$CellType = reorder(pheno_df2_subset$CellType, pheno_df2_subset$cell_order)
recurr_gram_fold_plot <- ggplot(pheno_df2_subset, aes(x = CellType, y= fold_change, fill = Phenotype)) +
  ggtitle("Recurrent gram-negative bacterial infections child terms") +
  geom_col() +
  geom_text(label = pheno_df2_subset$signif_asterisk, mapping = aes(y = fold_change + 1), size=8)+
  theme_cowplot() +
  scale_y_continuous(expand=c(0,0) ,limits= c(0,max(branch_signif_counts$n_signif)+2))+
  ylab("Fold enrichment") +
  xlab("Cell type") +
  theme(text = element_text(size = 16),axis.text.x = element_text(angle=90,hjust=1,vjust=0.2),plot.title = element_text(size=18, hjust = 0.5),legend.position = "none",strip.background = element_blank()) + 
  facet_wrap(~Phenotype, ncol=1, scales = "free_y") +
  scale_fill_manual(values= pal2)

figure_3 <- cowplot::plot_grid(recurrent_infections_plot, recurr_bact_fold_plot, recurr_gram_fold_plot, axis = "lr",
                               align = "v", ncol = 1, rel_heights = c(1.5, 4, 7),labels=c("A","B","C"), label_size=18)
```

## Figure 3

```{r fig_3_plot, fig.height=20, fig.width = 20, message = FALSE, warning = FALSE, echo = FALSE}

plot(figure_3)

png('figures/manuscript_fig_3.png',width = 400, height = 400)

print(figure_3)

pdf('figures/manuscript_fig_3.pdf', height=20, width=20)

print(figure_3)

dev.off()