---
title: "R Notebook"
output: html_notebook
---

```{r}
#Initialise
load("all_results_merged.rda") #Load results
if (!require("ggplot2")){
  install.packages("ggplot2")
}
if (!require("stringr")){
  install.packages("stringr")
}
library(ggplot2)
library(stringr)
genedata = read.delim("phenotype_to_genes.txt") #HPO annotation
colnames(genedata) = c("ID", "Phenotype", "EntrezID", "Gene", "Additional", "Source", "LinkID")
```

Just some starting data:

```{r}
x = data.frame(matrix(nrow=length(unique(all_results_merged$CellType)), ncol = 2))
for(i in 1:nrow(x)){
  x[i, 1] = unique(all_results_merged$CellType)[i]
}
x[1,] = unique(all_results_merged$CellType)
colnames(x) = c("Celltypes", "Totalq0phenotypes")

for(i in 1:nrow(x)){
  totalQ0 = length(all_results_merged$q[which(all_results_merged$CellType == all_results_merged$CellType[i] & all_results_merged$q==0)])
  x[i,2] = totalQ0
}
x$Totalq0phenotypes <- as.numeric(x$Totalq0phenotypes)

ggplot(x) + geom_bar(aes(x = Celltypes, y = Totalq0phenotypes), stat="identity") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

#Graph displaying the total number of phenotype-cell associations with adjusted p=0 for each cell type (level 1 classifications).
```
```{r}
###A general format for displaying relevant results:
print(subset(all_results_merged, q==0))[order(fold_change, decreasing = TRUE), ] 
#Displays results where q=0, in descending order of Z-score.
```

```{r}
###If you want to look at a specific cell type:
print(subset(all_results_merged, q==0 & CellType == "Hepatocytes"))[order(fold_change, decreasing = TRUE), ]
#Just replace with any of the cell types shown in the graph (chunk above)
```

```{r}
###Searching for specific phenotype labels:

#EG: HEART PHENOTYPES
HeartWords = c("(?i)heart", "(?i)cardiac", "(?i)aorta", "(?i)atrial")
phenotypesToUse <- unique(genedata$Phenotype[str_detect(genedata$Phenotype, pattern = HeartWords)])
print(subset(all_results_merged, q==0 & list %in% phenotypesToUse))[order(fold_change, decreasing = TRUE), ]
#Neatly search for key terms in the "list" column to pull relevant results. (?i) just allows case-insensitivity.
#Requires stringr package and "phenotype-to-genes.txt" from HPO.
```

```{r}
###Search for your key terms here:
KeyTerms = c("(?i)example")
phenotypesToUse <- unique(genedata$Phenotype[str_detect(genedata$Phenotype, pattern = KeyTerms)])
print(subset(all_results_merged, p<0.01 & q==0 & list %in% phenotypesToUse))[order(fold_change, decreasing = TRUE), ]
```

